### ISSUE TITLE
JIRA [IMG-1079] Template matching

### ISSUE THREAD

**Issue by thouis** [CellProfiler/CellProfiler#140] opened 2011-11-23 20:50 UTC
---------- Forwarded message ----------<br/>From: Misselwitz  Benjamin&lt;<a href='mailto:benjamin.misselwitz@micro.biol.ethz.ch'>benjamin.misselwitz@micro.biol.ethz.ch</a>&gt;<br/>Date: Sun, Aug 17, 2008 at 11:09<br/>Subject: MatchTemplate<br/>To:<a href='mailto:thouis@broad.mit.edu'>thouis@broad.mit.edu</a><br/><br/><br/>Hi Ray,<br/><br/>here, as promised the MatchTemplateTurbo module. I hope you can adopt<br/>it to the new CP-format.I made some very minor changes after our<br/>discussion (getting rid of the bwlabel command, I was wrong about the<br/>imageprops, they follow the object numbers in the FinalLabelMatrix<br/>image). I hope, you will not find any bugs... Please note, that we did<br/>not test all of the different shapes which can be defined in the menu<br/>for the Inner and OuterObjects. I am curious about the improvements<br/>you can still make!<br/><br/>The StandardCorrelation function was developed by Peter Horvarth, he<br/>is happy to contribute his code. The localMaximum function can be<br/>found at:<a href="http://www.mathworks.com/matlabcentral/files/14498/localMaximum.m">www.mathworks.com/matlabcentral/files/14498/localMaximum.m</a><br/>I do not know anything about licences... it is up to your judgement<br/>whether you can use it.<br/>Of course, as we discussed one year ago, I am happy to donate my code.<br/>If you need images for testing I have to discuss this with my<br/>collaborator in Basel.<br/><br/>Peter made another nice suggestion: He suggested to include the option<br/>to load a real image, or perhaps many images, instead of the<br/>ring-matrix. I did not have time to implement this.<br/><br/>I also include my MergeTemplate module... The idea was to screen for<br/>rings of different sizes and later merge the results, whereby the<br/>&quot;first&quot; ring (meaning first defined in the MergeTemplate module) would<br/>replace the second or third, if the different size rings would<br/>overlap. Against my advise, my collaborator in Basel refuses to do<br/>this :-)<br/>apparently, one ring is good enough... but the module should work.<br/>Include this or not in CP as you see fit.<br/><br/>I enjoyed or discussion a lot! Thank you for all your suggestions. We<br/>hope to meet you soon again in Zurich!<br/><br/>cheers, Benjamin<br/><br/>

Original reporter: mbray
Jira link: https://jira.broadinstitute.org/browse/IMG-1079
  (Original JIRA has attachments.)
Fix version: future
Assignee: mbray

**Comment by dlogan** [comment] 2016-02-02 00:40
Updated Forum post: http://forum.cellprofiler.org/t/extending-the-use-of-wormtools-to-drosophila-pupae/1948.

Closing now, for future consideration.

**Closed by dlogan** 2016-02-02 00:40 UTC
Labels: Feature request, Future consideration

**Comment by bethac07** [comment] 2016-08-16 14:04
Some sort of ability to template match would be really helpful for a number of projects-myelin in particular comes to mind.

**Comment by AnneCarpenter** [comment] 2016-09-07 18:31
Duplicate of #2261 so removing "future consideration" and leaving this issue closed.
