### ISSUE TITLE
TypeError using RunCellpose in CellProfiler

### ISSUE THREAD

**Issue by JulieNec** [CellProfiler/CellProfiler#4566] opened 2022-07-13 19:17 UTC
I am having trouble running Cellpose from within CellProfiler. I am able to use the Cellpose GUI without a problem, and have started training custom models on my images, which is great. However, when I try to use the RunCellPose module in CP on the same images, I get the following error:

`TypeError: catching classes that do not inherit from BaseException is not allowed`

Traceback gives the following:

`Traceback (most recent call last): File "c:\users\juliecn\documents\github\cellprofiler\cellprofiler\gui\pipelinecontroller.py", line 3390, in do_step self.__pipeline.run_module(module, workspace_model) File "c:\users\juliecn\documents\github\cellprofiler\core\cellprofiler_core\pipeline\_pipeline.py", line 1312, in run_module module.run(workspace) File "C:\Users\juliecn\Documents\GitHub\CellProfiler\CellProfiler-plugins\runcellpose.py", line 387, in run except float(cellpose_ver[0:3]) >= 0.7 and int(cellpose_ver[0])<2: TypeError: catching classes that do not inherit from BaseException is not allowed`

My images are Z stack grayscale .tif files. I have tried both processing as 3D and not as 3D, and I get the error in both cases. Other CP modules are working as normal on these images.

I am running CellProfiler 4.2.1 from and Cellpose 2.0 from source code using the instructions described [here](https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28Windows%29) and [here](https://github.com/MouseLand/cellpose#installation). To install CP, I cloned the CellProfiler and CellProfilerCore repositories to my own GitHub account. I am running on a Windows 10 computer using Python 3.8. 

I hope I have included all of the appropriate information. I am tagging the very helpful @carsen-stringer who offered to try to assist if needed. 

Thank you for the amazing resources everyone!

**Comment by bethac07** [comment] 2022-07-16 14:38
Closing here as a duplicate of https://github.com/CellProfiler/CellProfiler-plugins/issues/154 ; we will try over there to fix it!

**Closed by bethac07** 2022-07-16 14:38 UTC
Labels: Bug, Needs verification
