### ISSUE TITLE
CellProfiler 3 problems with wx module and ilastik

### ISSUE THREAD

**Issue by tannazg** [CellProfiler/CellProfiler#3636] opened 2018-09-07 12:24 UTC
Hi dear Community,
I am totally new to CellProfiler and I guess I am also a bit confused. I want to run the cell-profiler (I did the instructions completely(in the instruction it says, I would need wxgtk version 2.8) but when I come to the point of running cellprofiler.py in /opt/cellprofiler I face following Error:
```
/opt/CellProfiler$ python CellProfiler.py
ilastik import: failed to import the ilastik. Please follow the instructions on
    "ilastikdotorg" to install ilastik
Traceback (most recent call last):
  File "/opt/CellProfiler/cellprofiler/modules/classifypixels.py", line 71, in <module>
    from ilastik.core.dataMgr import DataMgr, DataItemImage
ImportError: No module named ilastik.core.dataMgr
ilastik import: failed to import the ilastik. Please follow the instructions on
                          "lastik.." to install ilastik
Traceback (most recent call last):
  File "/opt/CellProfiler/cellprofiler/modules/ilastik_pixel_classification.py", line 70, in <module>
    import ilastik_main
ImportError: No module named ilastik_main
Could not load cellprofiler.modules.exporttocellh5
Traceback (most recent call last):
  File "/opt/CellProfiler/cellprofiler/modules/__init__.py", line 294, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/opt/CellProfiler/cellprofiler/modules/exporttocellh5.py", line 29, in <module>
    import cellh5
  File "/usr/local/lib/python2.7/dist-packages/cellh5/__init__.py", line 12, in <module>
    from cellh5 import *
  File "/usr/local/lib/python2.7/dist-packages/cellh5/cellh5.py", line 18, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_wxagg.py", line 10, in <module>
    from . import wx_compat as wxc
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/wx_compat.py", line 32, in <module>
    raise ImportError(missingwx)
ImportError: Matplotlib backend_wx and backend_wxagg require wxPython>=2.9
could not load these modules: cellprofiler.modules.exporttocellh5
Uncaught exception in CellProfiler.py
Traceback (most recent call last):
  File "/opt/CellProfiler/cellprofiler/__main__.py", line 226, in main
    pipeline_path = pipeline_path)
  File "/opt/CellProfiler/cellprofiler/cellprofilerapp.py", line 24, in __init__
    super(CellProfilerApp, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7981, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7555, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/opt/CellProfiler/cellprofiler/cellprofilerapp.py", line 34, in OnInit
    from cellprofiler.gui.cpframe import CPFrame
  File "/opt/CellProfiler/cellprofiler/gui/cpframe.py", line 19, in <module>
    from cellprofiler.gui.pipelinelistview import PipelineListView
  File "/opt/CellProfiler/cellprofiler/gui/pipelinelistview.py", line 27, in <module>
    from cellprofiler.gui.cpfigure import window_name, find_fig
  File "/opt/CellProfiler/cellprofiler/gui/cpfigure.py", line 18, in <module>
    import matplotlib.backends.backend_wxagg
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_wxagg.py", line 10, in <module>
    from . import wx_compat as wxc
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/wx_compat.py", line 32, in <module>
    raise ImportError(missingwx)
ImportError: Matplotlib backend_wx and backend_wxagg require wxPython>=2.9
Failed to stop Ilastik
Exception fetching new version information from http://cellprofiler.org/CPupdate.html: <urlopen error [Errno -2] Name or service not known>
```
with /opt/CellProfiler$ pip freeze I get following:
amqp==2.3.2
ansible==1.7.2
apt-xapian-index==0.45
backports.functools-lru-cache==1.5
beautifulsoup4==4.2.1
boto==2.20.1
boto3==1.8.3
botocore==1.11.3
cell==0.0.3
cellh5==1.3.0
CellProfiler==3.1.5
centrosome==1.0.9
chardet==2.0.1
chemfp===1.1p1
cinfony==1.2
colorama==0.2.5
command-not-found==0.3
contextlib2==0.5.5
cvxopt==1.1.4
cycler==0.10.0
Cython==0.28.5
dask==0.18.2
debtagshw==0.1
decorator==3.4.0
defer==1.0.6
dirspec==13.10
docutils==0.11
future==0.16.0
futures==3.2.0
h5py==2.2.1
hmmlearn==0.2.0
html5lib==0.999
httplib2==0.8
inflect==1.0.0
ipython==1.2.1
javabridge==1.0.17
Jinja2==2.7.2
jmespath==0.9.3
joblib==0.7.1
JPype==0.5.4.2
kiwisolver==1.0.1
kombu==4.2.1
lxml==3.3.3
mahotas==1.4.4
MarkupSafe==0.18
matplotlib==2.2.3
MySQL-python==1.2.3
mysqlclient==1.3.13
nose==1.3.1
numexpr==2.2.2
numpy==1.11.0
oauthlib==0.6.1
oneconf==0.3.7.14.4.1
openbabel==1.7
openpyxl==1.7.0
PAM==0.4.2
pandas==0.13.1
paramiko==1.10.1
patsy==0.2.1
pexpect==3.1
Pillow==2.3.0
piston-mini-client==0.7.5
ply==3.4
Pmw==1.3.2
profiler==0.1.0
prokaryote==2.4.0
protobuf==3.0.0b2
psutil==1.2.1
py==1.4.20
pychecker==0.8.19
pycrypto==2.6.1
pycups==1.9.66
pycurl==7.19.3
Pygments==1.6
pygobject==3.12.0
PyHyphen==1.0b1
pyinotify==0.9.4
Pymacs==0.23
pymol==1.7.0.0
PyOpenGL==3.0.2
pyOpenSSL==0.13
pyparsing==2.0.1
Pypubsub==4.0.0
pyserial==2.6
pysmbc==1.0.14.1
pytest==2.5.1
python-apt===0.9.3.5ubuntu3
python-bioformats==1.4.0
python-dateutil==2.7.3
python-debian===0.1.21-nmu2ubuntu2
pytz==2012rc0
pyxdg==0.25
PyYAML==3.10
pyzmq==15.3.0
raven==6.9.0
reportlab==3.0
requests==2.2.1
roman==2.0.0
s3transfer==0.1.13
scikit-image==0.9.3
scikit-learn==0.14.1
scipy==0.13.3
sessioninstaller==0.0.0
simplegeneric==0.8.1
simplejson==3.3.1
six==1.11.0
software-center-aptd-plugins==0.0.0
ssh-import-id==3.21
statsmodels==0.5.0
style==1.1.0
subprocess32==3.5.2
tables==3.1.1
tensorflow==0.9.0
tornado==3.1.1
Twisted-Core==13.2.0
Twisted-Web==13.2.0
typing==3.6.6
update==0.0.1
urllib3==1.23
vboxapi==1.0
vine==1.1.4
virtualenv==1.11.4
wxGlade==0.6.8
wxmpl==2.0.0
wxPython==2.8.12.1
wxPython-common==2.8.12.1
xlrd==0.9.2
xlwt==0.7.5
zope.interface==4.0.5

I tried to upgrade wxPython gtk to version 3 but I get the message unable to locate the file and it seems impossible.I tried uninstalling the wxpython and installing it again too.
I guess I am too confused and I am trying a lot of different processes together, that I lost focus. Can somebody helps me what steps should I take to work with comet assay workflow in knime and to be able to run the cellprofiler node in knime? and to install cellprofiler itself ?
I do not know where I am stuck?
best
Tannaz

(I tried a lot to upgrade the wxPython package, which seems to be imposible it says:(Cannot uninstall 'wxPython'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.) and I also have installed the ilastik folder, but I do not know how and with which commend I have to import the module, since it does not have any setup.py file or bin file. 
in running example files I get also hundreds of import errors regarding another packets, that were not mentioned before. I appreciate if someone can help me with the installation, since I am quite new and beginner, so i dont see how I can move forward.
best
Tanni

**Comment by tannazg** [comment] 2018-09-07 12:38
Ilastik files I have downloaded too but I do not know how to import them as module since the script is run from a clone in /opt/ and not in the original path of the file and it does not have any setup.py file or it is not configured with ./configure and does not contain a bin data.

**Comment by AetherUnbound** [comment] 2018-09-08 02:13
Sorry you've been running into issues @tannazg! What system are you trying to install this on? Is it Linux or Mac? If you're on Linux and using Anaconda, you can run `conda install -c BjornFJohansson wxpython=3.0.2.0`. I suspect your issue may have been because you're running on wxpython 2.8.

**Comment by tannazg** [comment] 2018-09-10 07:19
@AetherUnbound Hi Mattew, yes it is Linux but I have not tried installing Anaconda. and yes I am running on wxpython 2.8

**Comment by tannazg** [comment] 2018-09-10 15:07
with Anaconda I have the same error again regarding backend-agg and ag

**Comment by tannazg** [comment] 2018-09-11 08:11
@AetherUnbound I made an environment with anaconda and now I have new errors, because I copied the ilastik python scripts in the cellprofiler folder. It seems that they are written in python 3 and not python 2.7 and they need to be modified. Is there any of those for python 2.7? or did everybody do the same for them?
the syntax errors:
Exception fetching new version information from http://cellprofiler.org/CPupdate.html: <urlopen error [Errno -2] Name or service not known>
Could not load cellprofiler.modules.classifypixels
Traceback (most recent call last):
  File "/opt/CellProfiler/cellprofiler/modules/__init__.py", line 294, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/opt/CellProfiler/cellprofiler/modules/classifypixels.py", line 71, in <module>
    from ilastik.core.dataMgr import DataMgr, DataItemImage
  File "/opt/CellProfiler/cellprofiler/modules/ilastik/__init__.py", line 91
    raise Exception(f'tried to convert non-string version: {vstring}')
                                                                    ^
SyntaxError: invalid syntax
Could not load cellprofiler.modules.ilastik_pixel_classification
Traceback (most recent call last):
  File "/opt/CellProfiler/cellprofiler/modules/__init__.py", line 294, in add_module
    m = __import__(mod, globals(), locals(), ['__all__'], 0)
  File "/opt/CellProfiler/cellprofiler/modules/ilastik_pixel_classification.py", line 70, in <module>
    import ilastik_main
  File "/opt/CellProfiler/cellprofiler/modules/ilastik_main.py", line 231
    f"Started thread: id={self.ident:x}, name={self.name}")
                                                         ^
SyntaxError: invalid syntax
could not load these modules: cellprofiler.modules.classifypixels,cellprofiler.modules.ilastik_pixel_classification
Failed to stop Ilastik

**Comment by AetherUnbound** [comment] 2018-09-13 04:15
Thanks for the update @tannazg. Failing to load modules shouldn't prevent cellprofiler from starting up appropriately (although it will print these exception messages at the beginning). Both `classifypixels` and `ilastik_pixel_classification` shouldn't be necessary for cellprofiler to run, they just won't be available on startup. Three questions:

1. Are you able to run cellprofiler, even though these modules fail on startup?
2. If not, are any other errors being thrown?
3. If so, are you running with `wxpython` at `3.0.2`?

**Comment by AetherUnbound** [comment] 2018-09-14 05:14
Okay taking a second look at it, I think this is most likely a `wxpython` version mismatch issue. I believe updating to `3.0.2`. Also, can you run `pip freeze` in the anaconda environment you're using for cellprofiler?

**Comment by AetherUnbound** [comment] 2018-09-30 01:04
I'm closing this, happy to re-open if the problem is not resolved.

**Closed by AetherUnbound** 2018-09-30 01:04 UTC
Labels: Environment/Install

**Comment by EMIDY643** [comment] 2024-12-08 19:46
I just came across an incredible tool that's incredibly useful! 🚀✨ If you want to give it a try, explore these resources for free access—no sign-up required! 🙌🔗
🔗 👉🔴 **### [Unlock AI magic for free here!](https://5454.us/)** ✅

🔗 👉 🔴### **[Explore free AI features now!](https://5454.us/)** ✅

🔗 👉🔴###  **_`[Get started with AI — no sign-up required!](https://5454.us/)`_** ✅
