### ISSUE TITLE
ReassignObjectNumbers: Per-parent unification performing inappropriate masking

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1789] opened 2016-02-29 19:48 UTC
In the attached pipeline (to be run with the two sample images), the three objects are made children of an overlapping parent object; these are unified per-parent in ReassignObjectNumbers. 

RelateObjects shows the desired outcome: the 3 objects are unified, with original boundaries intact.

However, in ReassignObjectNumbers, the 3 objects are basically masked, then unified.

![untitled-2](https://cloud.githubusercontent.com/assets/1186440/13406761/46dd569e-def3-11e5-999f-15f4d01ea9d5.png)
![untitled-1](https://cloud.githubusercontent.com/assets/1186440/13406762/46e3aea4-def3-11e5-9b44-e9d277cc2882.png)
[issue.cppipe.txt](https://github.com/CellProfiler/CellProfiler/files/151634/issue.cppipe.txt)

**Comment by LeeKamentsky** [comment] 2016-02-29 19:51
Any urgency, Mark?

**Comment by braymp** [comment] 2016-02-29 20:04
This is for a project I'm passing to @dlogan, so sometime before week's end if I want to test it. Otherwise, whenever :smile:

**Comment by LeeKamentsky** [comment] 2016-03-01 14:01
@dlogan @braymp 
It looks like the labels are masked on purpose. There's some discusion here: #297. I'm wondering if anyone is relying on the mask code - I can always do it both ways and give users the choice.

There are some oddities in the code. For instance, you have to run RelateObjects to define the parent / child relationship via the Parent_<child-object-name> measurement, but that measurement is never used. It's almost like someone decided to use the RelateObjects relationships, then changed their mind. 

You could do the following to use the measurement:

    renumbering = workspace.measurements[self.objects_name.value, "Parent_"+self.parent_objects.value]
    output_labels = renumbering[labels-1]

Does that make sense? I can change the unification method from ["Distance", "Per-parent"] to ["Distance", "Per-parent: overlap", "Per-parent: from RelateObjects"] (and please let me know what the wording should be for the choices).

**Comment by braymp** [comment] 2016-03-01 14:30
I think I wrote the per-parent code; who knows what the heck I was thinking :smile:  Just reading your commentary made me LOL.

I'm betting that when I wrote the code, I assumed that the children would always be enclosed by the parents (so masking makes sense). In this case, that's not true and bad things happen.

I'm thinking if per-parent unification (a) doesn't merge touching objects (as David pointed out in #297) and (b) re-labelling by some other method than masking, then no need to add an extra option.

**Comment by dlogan** [comment] 2016-03-06 11:52
[Batch 67](http://imagewebrhel6/batchprofiler/cgi-bin/ViewBatch.py?batch_id=67) that Mark seems to have submitted right after this fix is still erroring sometimes.  E.g. [this batch](http://imagewebrhel6/batchprofiler/cgi-bin/ViewTextFile.py?batch_array_id=89&task_id=7&file_type=text) which errors with 
```
Thu Mar  3 19:30:42 2016: Image # 7695, module RelateObjects # 16: 0.21 sec
Error detected during run of module ReassignObjectNumbers
Traceback (most recent call last):
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/redhat_6/20160302184944_d4787d3db13fc714fd75b12085a64689e49d24ba/cellprofiler/pipeline.py", line 1819, in run_with_yield
    self.run_module(module, workspace)
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/redhat_6/20160302184944_d4787d3db13fc714fd75b12085a64689e49d24ba/cellprofiler/pipeline.py", line 2067, in run_module
    module.run(workspace)
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/redhat_6/20160302184944_d4787d3db13fc714fd75b12085a64689e49d24ba/cellprofiler/modules/reassignobjectnumbers.py", line 299, in run
    copy_labels(objects.small_removed_segmented, output_labels)
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/redhat_6/20160302184944_d4787d3db13fc714fd75b12085a64689e49d24ba/cellprofiler/modules/reassignobjectnumbers.py", line 627, in copy_labels
    labels_new[segmented != 0] = seglabel[segmented[segmented != 0] - 1]
IndexError: index 127 is out of bounds for axis 0 with size 127
Thu Mar  3 19:30:42 2016: Image # 7695, module ReassignObjectNumbers # 17: 0.39 sec
```

Also related to #22 and #19 since BatchProfiler falsely reports "Complete" even with this error.

**Comment by dlogan** [comment] 2016-03-06 11:54
P.S. I can 't re-open this issue, apparently since I didn't open it.

**Comment by LeeKamentsky** [comment] 2016-03-08 16:44
I couldn't find any other failed jobs. I'm rerunning the one that failed after patching, so everything should be OK now.

**Comment by dlogan** [comment] 2016-03-09 19:04
Thanks - I have 9 jobs re-running that had failed.  @LeeKamentsky did you patch the same CPcluster version for this fix.  I just killed the jobs and they started re-running so I'm hoping so.

**Comment by LeeKamentsky** [comment] 2016-03-09 19:06
Yes. Patched /imaging/analysis/CPCluster/CellProfiler-2.0/redhat_6/20160302184944_d4787d3db13fc714fd75b12085a64689e49d24ba

**Comment by dlogan** [comment] 2016-03-09 19:10
:+1: So far, so good.  I will close this if the jobs don't error with the same issue, thanks.

**Comment by dlogan** [comment] 2016-03-14 16:47
All these jobs finished without error after patching.

**Comment by dlogan** [comment] 2016-03-28 15:18
These batches did complete.  However a number of objects have Cells_AreaShape_Area=0.  

See this database:
2015_07_14_RSV_SyncytiaQuantification_Janssen

which has these tables:
- phenix_2016_02_01_Per_Image
- phenix_2016_02_01_Per_Object
The very first object has Area=0.

Not sure if this ReassignObjectNumbers fix is the culprit, but it could be.

**Comment by LeeKamentsky** [comment] 2016-03-28 15:24
OK - will take a look at it today.

**Comment by LeeKamentsky** [comment] 2016-03-28 17:41
The area is zero because the cell centers have no secondary objects (from module number 17, ReassignObjectNumbers). The picture below has the cells numbered by their object number and you can see object number 1 has no secondary objects. So works as designed - perhaps a filter objects module to remove the cell centers without secondary objects?

![image](https://cloud.githubusercontent.com/assets/660469/14084852/c3f41a20-f4ea-11e5-8a37-b142ba72eb88.png)

**Comment by dlogan** [comment] 2016-03-28 18:56
I see, thanks for looking into this so quickly

**Comment by dlogan** [comment] 2016-04-08 13:27
I'm reopening this one because when I run in Test Mode with master on my Mac, I hit ReassignObjectNumbers and get:
```
Traceback (most recent call last):
  File "/Users/dlogan/github/CellProfiler/cellprofiler/gui/pipelinecontroller.py", line 2846, in do_step
    module.display(workspace, fig)
  File "/Users/dlogan/github/CellProfiler/cellprofiler/modules/reassignobjectnumbers.py", line 346, in display
    from cellprofiler.gui.cpfigure import renumber_labels_for_display
ImportError: cannot import name renumber_labels_for_display
```
Perhaps the import should be from cellprofiler.gui.cpfigure_tools rather than 
> from cellprofiler.gui.cpfigure import renumber_labels_for_display
?
https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/reassignobjectnumbers.py#L346

Though not sure why the patched version worked previously on the cluster?

**Comment by dlogan** [comment] 2016-04-08 13:40
[IllumFns.zip](https://github.com/CellProfiler/CellProfiler/files/210215/IllumFns.zip)
[ExampleImages.zip](https://github.com/CellProfiler/CellProfiler/files/210220/ExampleImages.zip)
[Issue1789.cppipe.zip](https://github.com/CellProfiler/CellProfiler/files/210199/Issue1789.cppipe.zip)

**Comment by LeeKamentsky** [comment] 2016-04-08 13:44
Can you fix it? I doubt I can get to it today.

**Comment by dlogan** [comment] 2016-04-08 13:46
Yup, just wanted to make sure I was on the right track.

**Closed** 2016-04-14 18:29 UTC
Labels: Bug
