### ISSUE TITLE
Feature Request: Combine two sets of objects into one set of objects, ObjectMath, or GroupObjects

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2705] opened 2017-04-19 20:59 UTC
There are situations when objects identified in separate channels or using different thresholds could be usefully combined into a single set of objects. For example, several cell types in a highly multiplexed image of tissue may be grouped together. Each cell type was defined in their own channel, but several could be closely related and should be processed together through a pipeline. Another example, is variable staining of nuclei that results in bright and dim nuclei. Each "type" of nuclei can be segmented properly by serially thresholding the image with *IdentifyPrimaryObjects*. The two sets of objects created using this strategy should be combined into a single set.

Currently, the solution is to convert all objects to images, use *ImageMath*, and then convert back to objects using *IdentifyPrimaryObject*. This requires combining several modules, whose purpose isn't immediately clear to a casual user of CellProfiler, and opens the door to unwanted variation in segmentation. This issue is related to #2704.

**Comment by braymp** [comment] 2017-04-19 21:21
(Kind of) a duplicate of #2140 (which is in turn is addressed by #876)? There, it says this is supplanted by #2151.

**Comment by karhohs** [comment] 2017-04-19 21:37
@braymp agreed. When searching for past issues I couldn't find #2140. However, what is status of #2140? It was closed and reopened and and #2151 is closed. Should I close this issue and bump #2140?

**Comment by braymp** [comment] 2017-04-20 00:01
I'm a bit confused myself. As I understand it, #2151 is the PR for #2140. So yes, it seems that giving #2140 a bump is the right thing to do.

**Comment by mcquin** [comment] 2017-04-20 12:39
Duplicate of #2140

**Closed by mcquin** 2017-04-20 12:39 UTC
