### ISSUE TITLE
Avoid CellProfiler shutdown when closing ImageJ window

### ISSUE THREAD

**Issue by imagejan** [CellProfiler/CellProfiler#1646] opened 2015-10-14 08:36 UTC
- Start CellProfiler
- Add the `RunImageJ` module to the empty pipeline
- Click the `Show` button to *Show ImageJ*
- Close the ImageJ window that just opened

The last step leads to shutdown of CellProfiler without warning. (Tested with CellProfiler 2.1.2 rev 207f5bf on Windows 7.)
I'm not sure if this has to be fixed on the ImageJ side though.

**Comment by LeeKamentsky** [comment] 2015-10-14 12:17
This is a duplicate of [issue #932](https://github.com/CellProfiler/CellProfiler/issues/932). The button needed to go away after https://github.com/CellProfiler/CellProfiler/pull/1581 because we now run ImageJ headless (no UI, so can't show ImageJ). The problem with closing was that there were elements that were largely out of our control that could quit ImageJ and close down the process.

We're revamping the build process so temporarily, the trunk builds page has your release at the latest - the page should be back up in a couple weeks.

**Closed** 2016-05-04 20:49 UTC
