### ISSUE TITLE
Add ilastik labels as inputs to CP's Classify

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1901] opened 2016-03-28 17:35 UTC
It would be nice to allow easy loading of ilastik (1.1+) training labels, for input into the new Classify module.  

Attached are a (very) small set of training labels saved as label matrices in ilastik 1.1.9, as tif and hdf5.  The input image (zipped here) is a single RGB composite from the ExampleFly images
[01_POS002_RGB.tif.zip](https://github.com/CellProfiler/CellProfiler/files/192183/01_POS002_RGB.tif.zip)

The training was named like this in their GUI:
![image](https://cloud.githubusercontent.com/assets/1225595/14084625/9527a85c-f4e9-11e5-8f0e-b3979715732a.png)

**Comment by braymp** [comment] 2016-03-28 17:49
Duplicate of #812?

**Comment by LeeKamentsky** [comment] 2016-03-28 17:50
nope - this is a feature for an experimental classify module - use Ilastik only as a data input tool

**Comment by dlogan** [comment] 2016-03-28 17:54
Sorry, here are the labels:
[labels_as_tif_and_h5.zip](https://github.com/CellProfiler/CellProfiler/files/192220/labels_as_tif_and_h5.zip)

**Comment by AnneCarpenter** [comment] 2016-09-03 00:52
@0x00b1 Is further work needed here? I see a commit Mar 28 but not sure whether it solves or has been merged or whatever.

**Comment by mcquin** [comment] 2018-02-11 04:29
Closing: no longer relevant. The Classify module has been removed from CellProfiler.

**Closed by mcquin** 2018-02-11 04:29 UTC
Labels: Feature request
