### ISSUE TITLE
Renumbering when loading image type object

### ISSUE THREAD

**Issue by rsenft1** [CellProfiler/CellProfiler#4485] opened 2021-12-02 14:39 UTC
**Describe the bug**
Issue described [here](https://forum.image.sc/t/load-image-type-object-cp4-2-1-vs-cp4-0-7/60105). In CP 4.2.1, converting objects to image and saving produces a label matrix with objects numbered 1 to n in increasing number from left to right. However, this numbering is inconsistent with loading that label matrix as objects, which renumbers objects from 1 to n from top to bottom of the image. Inconsistency in object number can present issues if tracking objects across multiple pipelines/complex workflows. 

**Screenshots**
Can be found [here](https://forum.image.sc/t/load-image-type-object-cp4-2-1-vs-cp4-0-7/60105)

**Comment by callum-jpg** [comment] 2022-02-07 21:46
The source of this behaviour is commit 2dbaf25 in cellprofiler core, which uses skimage.morphology.label to sequentially label objects that have been imported from a file in NamesAndTypes. This was to fix #4403. The way in which labels are generated in ConvertObjectsToImage (I think) should be updated to match the way in which labels are generated in NamesAndTypes.

**Comment by bethac07** [comment] 2022-02-08 15:03
Yup! If label doesn't have a way to parameterize this, a good "dumb" way to do this would be to rotate the image, label, and then flip back :)

**Comment by rsenft1** [comment] 2022-02-09 17:10
Thanks @callum-jpg !

**Comment by nicolas-froment** [comment] 2022-02-09 17:30
Hi All, 

Thanks for the analysis. I would just like to understand the "close" status : Does it mean that #4403 will be included n the next CP 4.2.x ? Or do you think we should consider the "dumb" solution?

**Comment by bethac07** [comment] 2022-02-09 17:59
Yeah, we shouldn't close this until a fix is pulled

**Comment by rsenft1** [comment] 2022-02-09 18:12
Whoops sorry, I didn't realized we hadn't pulled a fix yet. Thanks for reopening!

**Comment by bethac07** [comment] 2022-02-09 23:48
So this is definitely weird, in a way I'm having a hard time figuring out

This sort of relabeling does NOT happen in dummy data
![image](https://user-images.githubusercontent.com/6721515/153309347-81bb2e00-3ecd-4a30-b374-71e8beec89e8.png)

But it is very clearly happening in the input modules, and not in CellProfiler's pixel assignment or anything, specifically in the label call:
![image](https://user-images.githubusercontent.com/6721515/153309437-1c03e7e9-3668-4344-a0c7-283ca4ebfeb3.png)

```
In [4]: numpy.unique(input_dummy[75:106,19:50])
Out[4]: array([ 0, 18, 27, 30], dtype=int32)

In [5]: numpy.unique(dummy[75:106,19:50])
Out[5]: array([ 0, 10, 11, 28])
```

I'd rather avert the problem than hacky-fix it, and ideally to understand it too, but I'll settle for just avert.

**Comment by bethac07** [comment] 2022-02-10 14:02
So the way this happens in, for example, [MaskObjects is to do this](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/maskobjects.py#L372-L376)
```
        if self.retain_or_renumber == R_RENUMBER:
            unique_labels = numpy.unique(labels[labels != 0])
            indexer = numpy.zeros(nobjects + 1, int)
            indexer[unique_labels] = numpy.arange(1, len(unique_labels) + 1)
            labels = indexer[labels]
            parent_objects = unique_labels
```
But I'm pretty sure that strategy isn't going to work for us, because it is essentially designed to handle labels dropping out, not changing their order.

This definitely WILL reorder data (though someone should check it for 3D), though it's possible/probable I'm forgetting some numpy function that would clean the middle up a bit
```
def relabel_objects(initial_labels):
    label_values, label_indices = numpy.unique(
        initial_labels[initial_labels!=0].flatten(),
        return_index = True)
    label_indices_list = list(label_indices)
    label_indices_sorted = list(label_indices) 
    label_indices_sorted.sort()
    mapper = numpy.array([0]+[label_indices_sorted.index(x)+1 for x in label_indices_list])
    return mapper[initial_labels]
```

![image](https://user-images.githubusercontent.com/6721515/153423198-829083e7-9db1-4a22-9e60-975c04088fc2.png)

**Comment by bethac07** [comment] 2022-02-10 15:30
@rsenft1 makes a good point that we should just avoid this entirely most of the time by putting in a check that max label value is > number of label values

**Comment by rsenft1** [comment] 2022-02-10 23:08
Does the function you've outlined above work if you have non-contiguous object numbers though? Like if someone has removed an object or is taking a label matrix made elsewhere that is not labeled _1-n_. 
`initial_labels_nc = numpy.array([[1,0,3,3],[4,4,0,7],[4,4,0,7],[0,0,6,5]])`
![image](https://user-images.githubusercontent.com/28116530/153510188-07239757-6f7a-41d4-bb69-7046283f015a.png)
When I try to run `relabel_objects(initial_labels_nc)`, I get`IndexError: index 7 is out of bounds for axis 0 with size 7` from the last line where the initial_labels array is being used as indices for mapper. 

Perhaps there's a good place to handle this elsewhere, but I took a stab at 1) having a check for contiguous labeling and passing if object numbers are OK and 2) if non-contiguous labeling is used, relabel before your index sorting. It's much faster with label matrices that are contiguous because it doesn't call numpy.unique() and (I think) it correctly handles the non-contiguous ones using the same labeling strategy you're using here. It's slower than before if it has a non-contiguous matrix because of the additional replacement (which comes from [this SO discussion](https://stackoverflow.com/questions/45735230/how-to-replace-a-list-of-values-in-a-numpy-array)), but maybe there's a way to optimize it. 

```
def relabel_objects_revised(initial_labels):
    #quick check if renumbering is necessary
    flat_mat=initial_labels.flatten()
    actual_values=list(set(flat_mat))
    contig_values = numpy.arange(max(flat_mat)+1).tolist()
    if actual_values==contig_values:
        return initial_labels
    label_values, label_indices = numpy.unique(
        flat_mat[flat_mat!=0],
        return_index = True)
    replacer = dict(zip(actual_values, contig_values))
    mat_list = flat_mat.tolist()
    contig_mat = numpy.array(list(map(replacer.get, mat_list, mat_list)))
    contig_mat= contig_mat.reshape(initial_labels.shape)
    label_indices_list = list(label_indices)
    label_indices_sorted = list(label_indices) 
    label_indices_sorted.sort()
    mapper = numpy.array([0]+[label_indices_sorted.index(x)+1 for x in label_indices_list])
    return mapper[contig_mat]
```

Testing out some timings:
```
initial_labels = numpy.array([[1,0,3,3],[4,4,0,2],[4,4,0,2],[0,0,6,5]])
initial_labels_nc = numpy.array([[1,0,3,3],[4,4,0,7],[4,4,0,7],[0,0,6,5]])

timeit.timeit('relabel_objects(initial_labels)', number=10000, globals=globals()).       # -> 0.2009
timeit.timeit('relabel_objects_revised(initial_labels)', number=10000, globals=globals()) # -> 0.077

timeit.timeit('relabel_objects(initial_labels_nc)', number=10000, globals=globals()) # Errors
timeit.timeit('relabel_objects_revised(initial_labels_nc)', number=10000, globals=globals()) # -> 0.3291
```
The output with the non-contiguously labeled matrix is: 
![image](https://user-images.githubusercontent.com/28116530/153511956-9cd59dee-f3e8-421f-8e35-46423d0f81ba.png)

**Comment by bethac07** [comment] 2022-02-10 23:42
Nope, I did not test it on LITERALLY the case I was trying to solve for (non-contiguous labels). Nice catch :)

I think there probably are some things to be optimized in your middle section there but I'll take a look later.

**Comment by rsenft1** [comment] 2022-02-11 16:06
Ah, I just realized the contig_values should be based on the length of the set of values, not on its max. I played around with some alternate ways of doing this. 
```
def relabel_objects_revised(initial_labels):
    #quick check if renumbering is necessary
    flat_mat=initial_labels.flatten()
    actual_values=list(set(flat_mat))
    contig_values = numpy.arange(len(actual_values)).tolist()
    if actual_values==contig_values:
        return initial_labels
    label_values, label_indices = numpy.unique(
        flat_mat[flat_mat!=0],
        return_index = True)
    replacer = dict(zip(actual_values, contig_values))
    mat_list = flat_mat.tolist()
    contig_mat = numpy.array(list(map(replacer.get, mat_list, mat_list)))
    contig_mat= contig_mat.reshape(initial_labels.shape)
    label_indices_list = list(label_indices)
    label_indices_sorted = list(label_indices) 
    label_indices_sorted.sort()
    mapper = numpy.array([0]+[label_indices_sorted.index(x)+1 for x in label_indices_list])
    return mapper[contig_mat]
```
vs a slightly different strategy:
```
def relabel_objects_revised_nodict(initial_labels):
    #quick check if renumbering is necessary
    flat_mat=initial_labels.flatten()
    actual_values=numpy.asarray(list(set(flat_mat)))
    contig_values = numpy.arange(len(actual_values))
    if all(actual_values==contig_values):
        return initial_labels
    _, label_indices = numpy.unique(
        flat_mat[flat_mat!=0],
        return_index = True)
    replacer = numpy.arange(0,actual_values.max() + 1)
    replacer[actual_values] = contig_values
    contig_mat = replacer[flat_mat]
    contig_mat= contig_mat.reshape(initial_labels.shape)
    label_indices_list = list(label_indices)
    label_indices_sorted = list(label_indices) 
    label_indices_sorted.sort()
    mapper = numpy.array([0]+[label_indices_sorted.index(x)+1 for x in label_indices_list])
    return mapper[contig_mat]
```

Both have pretty similar timing: 
```
timeit.timeit('relabel_objects_revised(initial_labels_nc)', number=10000, globals=globals()) #0.33
timeit.timeit('relabel_objects_revised_nodict(initial_labels_nc)', number=10000, globals=globals()) #0.34
```

If we really want to speed it up, we could remove the CP-like renumbering (and therefore avoid the call to numpy.unique()
```
def relabel_objects_revised_noCPreorder(initial_labels):
    #quick check if renumbering is necessary
    flat_mat=initial_labels.flatten()
    actual_values=numpy.asarray(list(set(flat_mat)))
    contig_values = numpy.arange(len(actual_values))
    if all(actual_values==contig_values):
        return initial_labels
    replacer = numpy.arange(0,actual_values.max() + 1)
    replacer[actual_values] = contig_values
    contig_mat = replacer[flat_mat]
    contig_mat= contig_mat.reshape(initial_labels.shape)
    return contig_mat
```
This is much faster:
`timeit.timeit('relabel_objects_revised_noCPreorder(initial_labels_nc)', number=10000, globals=globals()) # 0.15`

The output in general preserves more of the original object numberings: 
![image](https://user-images.githubusercontent.com/28116530/153624468-0aa787ad-8c5a-470d-820d-2c84ea53d7fb.png)
However, the labeling doesn't follow the left-to-right ordering of CP. It just starts replacing when there's an expected value missing. I can't really see why this would be a huge issue given we're allowing label matrices made in other programs that might have a different labeling convention from CP but maybe there's something I'm not thinking about downstream that makes this a bad idea.

**Comment by rsenft1** [comment] 2022-02-14 16:59
Another slight optimization: 
```
def relabel_objects_revised_noCPreorder(initial_labels):
    #quick check if renumbering is necessary
    flat_mat=initial_labels.flatten()
    actual_values=numpy.asarray(list(set(flat_mat)))
    contig_values = numpy.arange(len(actual_values))
    if all(actual_values==contig_values):
        return initial_labels
    replacer = numpy.arange(0,actual_values.max() + 1)
    replacer[actual_values] = contig_values
    contig_mat = replacer[flat_mat]
    contig_mat= contig_mat.reshape(initial_labels.shape)
    return contig_mat
```
`timeit.timeit('relabel_objects_revised_noCPreorder(initial_labels_nc)', number=10000, globals=globals())
Out[948]: 0.1294956428464502`

However, all of these strategies get slow when we start working with big label matrices. I'm not show how to avoid this issue: 
```
large_test = numpy.random.randint(100, size=(1000, 1000))

timeit.timeit('relabel_objects_revised_noCPreorder(large_test)', number=100, globals=globals())
Out[950]: 6.041195494122803
```
Is 6 seconds for 100 1000 x 1000 matrices too slow?

**Comment by bethac07** [comment] 2022-02-17 17:26
@rsenft1 , do you mind timing if you still have your notebook, the CellProfiler way to do the renumbering I posted above (which I've reproduced below into a function for your convenience)?  I originally ruled it out because it wasn't performing a CellProfiler-like-reordering, but I think I'm convinced by your argument that it isn't necessary to do that.

```
def renumber_per_CellProfiler(labels):
    nobjects = numpy.max(labels)
    unique_labels = numpy.unique(labels[labels != 0])
    indexer = numpy.zeros(nobjects + 1, int)
    indexer[unique_labels] = numpy.arange(1, len(unique_labels) + 1)
    labels = indexer[labels]
    return labels
```

**Comment by rsenft1** [comment] 2022-02-17 18:31
That one is faster!
`timeit.timeit('renumber_per_CellProfiler(large_test)', number=100, globals=globals())` returns 4.29 s

I made a slight change and added in a check for whether the label matrix already meets criteria (not necessary if we're checking somewhere else, but will speed things up if every label matrix gets processed by this function: 

```
def renumber_per_CellProfiler_revise(labels):
    nobjects = numpy.max(labels)
    unique_labels = numpy.unique(labels[labels != 0])
    contig_labels=numpy.arange(1, len(unique_labels) + 1)
    if all(unique_labels==contig_labels):
       return labels
    indexer = numpy.zeros(nobjects + 1, int)
    indexer[unique_labels] =contig_labels
    labels = indexer[labels]
    return labels
```
For reasons I do not entirely understand, this reordering also seems to make things a little faster:
`timeit.timeit('renumber_per_CellProfiler_revise(large_test)', number=100, globals=globals())` returns 3.88 s

I've rerun it a few times and it is consistently faster ~3.8 s vs ~4.2-4.3 s. I guess moving making contig_values earlier makes this faster than defining it at the same time as replacing the indexer.

**Comment by rsenft1** [comment] 2022-03-08 20:10
I've added these changes to namesandtypes.py in core and have verified that this fixes the issues experienced with 
1) numbering not matching between saving a label matrix and loading it 
2) non-continuous matrices are relabeled

The same commit 2dabaf25 also made changes to the namesandtypes test functions, but I [took a look](https://github.com/CellProfiler/core/blob/master/tests/modules/test_namesandtypes.py#L1910-L1943) and it appears that there are not any changes needed to adjust for this renumbering change (the current test functions do not check whether labels are correct, just that they have the expected size and so they pass). Should I write a new test?

**Comment by bethac07** [comment] 2022-07-15 19:32
I agree that we just in general aren't interested in supporting non-consecutive label matrices (anymore) and thus should tell folks to either a) load as images and use ConvertImagesToObjects and/or b) load as objects AND images and use MeasureObjectIntensity to get the previous value for whatever it is you need. In that case, are we ready to pull https://github.com/CellProfiler/core/pull/96 ?

**Comment by rsenft1** [comment] 2022-07-15 21:24
Yep I think so!

**Comment by bethac07** [comment] 2022-07-16 14:32
Closed by https://github.com/CellProfiler/core/pull/96

**Closed by bethac07** 2022-07-16 14:32 UTC
Labels: Bug, Needs verification
