### ISSUE TITLE
Option to select folders in Image module

### ISSUE THREAD

**Issue by tischi** [CellProfiler/CellProfiler#1947] opened 2016-03-31 11:55 UTC
@LeeKamentsky 
Right-clicking in the Image module only gives the option "Browse for Images".
It would be really good if it also gave the option "Browse for Image-containing Folders".
This is important if the drag and drop does not work, e.g. when launching CellProfiler "in the could", e.g., on a remote computer with X forwarding to see the GUI.

**Comment by braymp** [comment] 2016-03-31 16:43
Duplicate of #600?

**Comment by 0x00B1** [comment] 2016-03-31 18:04
@braymp:
> Duplicate of #600?

Yep

**Closed by 0x00B1** 2016-03-31 18:04 UTC
