### ISSUE TITLE
CreateBatchFiles and wx error

### ISSUE THREAD

**Issue by icyhearted** [CellProfiler/CellProfiler#2740] opened 2017-05-02 20:14 UTC
I run a python script on a cluster as:
"import cellprofiler.pipeline

pipeline = cellprofiler.pipeline.Pipeline()

pipeline.load("w.cppipe")

measurements = pipeline.run()"

w.cppipe is the pipeline file.

But I have got the following screen shot:

![capture](https://cloud.githubusercontent.com/assets/28314244/25637161/134a4200-2f52-11e7-9e07-ed1028bb5321.PNG)

Since I am pretty new in this area of python and cellprofiler, here are my questions:

How can I add input and output directory into the python script?
How can I run cell profiler in a headless mode, what's the python coding for that?

Thanks,

icyhearted

**Comment by mcquin** [comment] 2017-05-03 14:44
Hi @icyhearted . Your cluster environment probably doesn't have wxPython installed because it's not required for running CellProfiler headlessly. You can get around this by adding these lines:

```python
import cellprofiler.preferences

cellprofiler.preferences.set_headless()
```

**Comment by mcquin** [comment] 2017-05-05 13:22
Closing this issue because it is not a bug not a feature request/enhancement.

**Closed by mcquin** 2017-05-05 13:22 UTC
