### ISSUE TITLE
No output generated when running headless

### ISSUE THREAD

**Issue by Hetty17** [CellProfiler/CellProfiler#2696] opened 2017-04-13 08:35 UTC
I am trying to analyse 2268 images, grouped into 108 wells (21 images/ sites per well), headless. I have specified to save spreadsheet to default output folder subfolder, named by Well metadata (to prevent output files being overwritten when run in parallel on a cluster). However, I have getting the output folders with no files in them. 

The code I used was: 
output="/home/kjf/projects_kjf/Output_Donor1/well$idx" && mkdir $output
cellprofiler -r -c -i /home/kjf/projects_kjf/Donor1 -o $output -g Metadata_Well=$idx -p /home/kjf/Cell_Painting/FastAnalysis_Donor1.cpproj $range

This gave me output folders 1-108 each with a folder for each well within them... with no output files in them 

I am now trying: 

cellprofiler -r -c -i /home/kjf/projects_kjf/Donor1 -o /home/kjf/projects_kjf/Output_Donor1 -g Metadata_Well=$w -p /home/kjf/Cell_Painting/FastAnalysis_Donor1.cpproj for set ranges of 21 images per node. 

I have tried variations on specifying grouping and ranges before inducing cellprofiler as above.

The pipeline has worked before and no one was able to see any problems in my pipeline or headless code: http://forum.cellprofiler.org/t/exporttospreadsheet-output-location-headless-command-line/2140/6
The pipeline is attached to this forum question.

It was suggested by Beth Cimini that is could be a software issue.  Or at the very least the software engineers would be my last port of call!  Is there anything you can recommend?

Thanks!!!

**Comment by mcquin** [comment] 2017-04-13 18:32
Hi @Hetty17 which version of CellProfiler are you running?

Does CellProfiler emit a message like:

```
CP-JAVA 14:31:42.395 [Thread-1] WARN  o.c.imageset.ChannelFilter - Empty image set list: no images passed the filtering criteria.
```

**Comment by Hetty17** [comment] 2017-04-14 09:06
Hi,

I am running version 2.2.0 and I don't get that error.  I can watch the log and see it run through all the modules, it just doesnt create output .csvs.  I can also run in with a GUI on just a few images on my laptop to check that it does pass metadata and names and types correctly.

**Comment by Hetty17** [comment] 2017-04-14 11:34
Here is the code I use to start:
cellprofiler --plugins-directory /home/kjfg732/Cell_Painting/plugins -r -c -i /home/kjfg732/projects_kjf732/Donor1 -o /home/kjfg732/Output_Donor1/FinalFastAnalysis_Donor1 -g Metadata_Well=$idx -p /home/kjfg732/Cell_Painting/FinalFastAnalysis_Donor1.cpproj

**Comment by Hetty17** [comment] 2017-04-14 11:39
[log.docx](https://github.com/CellProfiler/CellProfiler/files/921985/log.docx)

**Comment by mcquin** [comment] 2017-04-14 20:43
> The pipeline has worked before and no one was able to see any problems in my pipeline or headless code

Has anything changed since? CellProfiler version? Did you reinstall CellProfiler? Has your operating system changed?

**Comment by mcquin** [comment] 2017-04-14 20:44
Can you please send me a plain .txt file?

**Comment by Hetty17** [comment] 2017-04-15 06:57
I added grouping and named the output files by metadata well, to prevent overwriting when running in batch. That is all that changed.  And that works when I run it on one computer (everything else the same).

I can see the pipeline work all the way through, when i had uniquely named output folder (instead of uniquely named files that I have now), it created the folders just didnt save any output files in them.

[cellp_FinalFastAnalysis_Donor1_2017-04-14.txt](https://github.com/CellProfiler/CellProfiler/files/923397/cellp_FinalFastAnalysis_Donor1_2017-04-14.txt)

**Comment by mcquin** [comment] 2017-04-18 12:06
Are you using the same copy of the pipeline on both computers? Are both computers running the same version of CellProfiler?

**Comment by mcquin** [comment] 2017-04-18 12:09
Also, I don't understand what you mean by "uniquely named files" for output. I do see that you are exporting to subfolders.

**Comment by Hetty17** [comment] 2017-04-18 12:38
Yes I am using the same version of the pipeline and of CellProfiler.  Any changes I make to the pipelines I make on my laptop connected to the cluster, so all changes are made on the same computer, same cellprofiler, same pipeline anyway.

And the pipeline creates output subfolders with unique names – the name of the well processed.

**Comment by bethac07** [comment] 2017-04-19 13:25
Your stack trace actually does show an error:
```

Failed to complete post_run processing for module MeasureImageQuality.
Traceback (most recent call last):
  File "/opt/az/broadinstitute/cellprofiler/2.2.0/lib/python2.7/site-packages/cellprofiler/pipeline.py", line 2217, in post_run
    module.post_run(workspace)
  File "/opt/az/broadinstitute/cellprofiler/2.2.0/lib/python2.7/site-packages/cellprofiler/modules/measureimagequality.py", line 752, in post_run
    statistics += self.calculate_experiment_threshold(image_group, workspace)
  File "/opt/az/broadinstitute/cellprofiler/2.2.0/lib/python2.7/site-packages/cellprofiler/modules/measureimagequality.py", line 1087, in calculate_experiment_threshold
    threshold_group.threshold_feature_name(image_name))
  File "/opt/az/broadinstitute/cellprofiler/2.2.0/lib/python2.7/site-packages/cellprofiler/measurements.py", line 1032, in get_all_measurements
    self.get_image_numbers())
  File "/opt/az/broadinstitute/cellprofiler/2.2.0/lib/python2.7/site-packages/cellprofiler/measurements.py", line 960, in get_measurement
    vals = self.hdf5_dict[object_name, feature_name, image_set_number]
  File "/opt/az/broadinstitute/cellprofiler/2.2.0/lib/python2.7/site-packages/cellprofiler/utilities/hdf5_dict.py", line 364, in __getitem__
    assert feature_exists
AssertionError
```

**Comment by Hetty17** [comment] 2017-04-19 13:26
Do you know what this means?

**Comment by bethac07** [comment] 2017-04-19 13:38
It means that something in calculating the post-run Experiment metrics for MeasureImageQuality failed, which is why you're not getting output.

Can you try un-checking the Experiment->ImageQuality measurement (see below) and see if your pipeline works then?

![image](https://cloud.githubusercontent.com/assets/6721515/25182799/c09271a4-24e3-11e7-9b5d-b6066c9692e6.png)

**Comment by Hetty17** [comment] 2017-04-20 08:00
I tried it as you suggested and still no outputs.  I have tried the pipeline without grouping and it works, but when I group - in order to have unique output names or locations - it fails to produce outputs.  Is there any known issues that this could be?

**Comment by mcquin** [comment] 2017-04-20 12:30
Do you have another error in your output?

**Comment by Hetty17** [comment] 2017-04-20 12:35
The only other that I can find is: 
run: error: find_node_record: lookup failure for zoi-001
srun: error: find_node_record: lookup failure for zoi-002
srun: error: find_node_record: lookup failure for zoi-003

but this doesnt stop the nodes from running the pipeline

**Comment by bethac07** [comment] 2017-04-20 13:03
My guess is that there must be some other error in the stack trace; can you check again?  
If you can't find one, try un-checking the entire 'Experiment' category and see if that now produces output.

**Comment by Hetty17** [comment] 2017-04-20 14:03
Exception TypeError: "'NoneType' object is not callable" in '_javabridge.JB_Object.__dealloc__' ignored

is the only other error there

**Comment by mcquin** [comment] 2017-04-20 15:43
Please send another stack trace.

**Comment by mcquin** [comment] 2017-05-05 13:28
Closing due to lack of follow up and reproducibility.

**Closed by mcquin** 2017-05-05 13:28 UTC
Labels: Needs verification
