### ISSUE TITLE
Error when ExportToSpreadsheet and ExportToDatabase are

### ISSUE THREAD

**Issue by bdiazroh** [CellProfiler/CellProfiler#4471] opened 2021-10-08 13:09 UTC
When running a pipeline that contains bot "ExportToSpreadsheet" and "ExportToDatabase" an error occurs at the end of the analysis.  "AssertionError: Feature Count_ExportToDb for Image does not exist"

The error occurs independent of the order of the modules, but if either one of the modules is turned off, the analysis completes and exports all expected files correctly.

<img width="372" alt="Screen Shot 2021-10-08 at 8 57 47 AM" src="https://user-images.githubusercontent.com/82409851/136561996-06caff3e-da25-4951-a6bd-be5dc90975cc.png">

**Desktop:**
 - OS: BigSur 11.6
 - CellProfiler Version 4.2.1
 - Cloned from source

**Comment by bwharram** [comment] 2021-11-18 20:51
I had the same error, thanks for the workaround!

**Comment by amgfernandes** [comment] 2021-12-01 13:37
I got the same error. Same configuration as @bdiazroh. The only workaround is to deactivate one of the modules. 

Link to assertion line:       https://github.com/CellProfiler/core/blob/464867aca9556a96ef80cdf928d2939e3943753d/cellprofiler_core/utilities/hdf5_dict.py#L422

**Comment by bethac07** [comment] 2022-07-18 23:28
I'm 99% certain this was fixed by #4449 ; I can no longer reproduce in current master and it looks like that would fix it. Closing, reopen if we can restart it.

**Closed by bethac07** 2022-07-18 23:28 UTC
Labels: Bug, Needs verification
