### ISSUE TITLE
Documentation - Does IdPrimary need this in "What do I get as output?"

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3187] opened 2017-09-15 22:56 UTC
If someone can confirm that the content here is true for IdentifyPrimary, we need to add it in to the help (around line 146 but there is a PR pending and I don't want to screw things up). I got this text from IdentifySecondaryObjects. It goes at the beginning of the "What do I get as output?" section of the intro help for the module.

We probably need to put this text into a help blob that we can reference from IdPrimary and other modules that recently had their save-outlines options removed. This recent issue removed the outline-saving option so the modules listed there probably need this blurb too #3035 . 

 ```
Once the module has finished processing, the module display window will
 show the following panels;
 note that these are just for display: you must use the **SaveImages** 
 module if you would like to save any of these images to the hard drive
 (as well, the **OverlayOutlines** module or **ConvertObjectsToImage**
 modules might be needed):

```

**Comment by braymp** [comment] 2017-09-15 23:08
I think this blurb is misleading. 
* Yes, you would need to use the SaveImages module but it's not as if the display panels are (or were ever) retained somewhere for saving purposes. 
* You would need to reconstruct them using OverlayOutlines and ConvertObjectsToImage ("might be needed" makes it sound like its optional).

**Comment by AnneCarpenter** [comment] 2017-09-15 23:17
Great feedback. Is this better then? 

```
Once the module has finished processing, the module display window will
show the following panels. Note that these are just for display: you must
use the **SaveImages** module if you would like to save any of these
images to the hard drive (as well, you will need to construct the desired
images using **OverlayOutlines** or **ConvertObjectsToImage**).
```

**Comment by braymp** [comment] 2017-09-15 23:26
Close. I think something like this would do it:
```
Once the module has finished processing, the module display window will
show the following panels. Note that these visualizations are just for 
display: if you would like to save them to your hard drive, you will need 
to reconstruct them using the **OverlayOutlines** and/or **ConvertObjectsToImage** 
modules followed by the **SaveImages** module.
```

**Comment by AnneCarpenter** [comment] 2017-09-15 23:44
perfect! Needs someone other than me to make the help blob and assess the list of modules that need this.

**Comment by minh-doan** [comment] 2017-09-20 20:09
Taking this , (hopefully) requires less brain than others

**Comment by mcquin** [comment] 2017-09-20 20:10
@minh-doan Apologies for closing another issue, but I think this is a duplicate of https://github.com/CellProfiler/CellProfiler/issues/3198

**Closed by mcquin** 2017-09-20 20:10 UTC
Labels: Documentation

**Comment by AnneCarpenter** [comment] 2017-09-20 20:23
Poor Minh, what luck!

The text in 3198 doesn't quite  capture the "No, you can't have the images straight from the display without some work" aspect of this, but I think it's worth having it a little less clear so that it's universally applicable and can be edited in sync.

**Comment by minh-doan** [comment] 2017-09-20 20:30
😂 
100% agree on "universally applicable" though
