### ISSUE TITLE
Download hyperlinks in welcome window don't to anything

### ISSUE THREAD

**Issue by ljosa** [CellProfiler/CellProfiler#954] opened 2013-12-06 17:46 UTC
(Only on Linux.)

**Comment by mcquin** [comment] 2018-02-11 04:24
@AetherUnbound could you check the welcome screen links on Linux? We'll close this issue if you cannot reproduce.

**Comment by AetherUnbound** [comment] 2018-02-12 17:02
All of the links work on my machine! I'll close this issue.

**Closed by AetherUnbound** 2018-02-12 17:02 UTC
Labels: Needs verification
