### ISSUE TITLE
Lazy load modules

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#1715] opened 2015-11-24 16:26 UTC
We should lazy load modules (i.e. we should only load a module when someone pops it onto their pipeline or a pipeline is opened).

**Comment by 0x00B1** [comment] 2016-05-18 22:11
An immediate strategy is to move some of the modules into the plugin package.

**Comment by mcquin** [comment] 2017-04-21 17:15
Duplicate of #2168

**Closed by mcquin** 2017-04-21 17:15 UTC
Labels: Feature request
