### ISSUE TITLE
CentOS6.2 CP 2.1.1 build issue

### ISSUE THREAD

**Issue by psteadman** [CellProfiler/CellProfiler#1345] opened 2015-04-17 14:50 UTC
Hello,

I would've posted this on the forum but the captcha link isn't showing up so I couldn't register.

I am trying to use cell profiler on a centsOs 6.2 system which is part of a cluster. The machine I am on has 32 threads. When I launch cell profiler the jvm tries to launch 32 worker threads which is not possible since this is a shared system. Here is my output:

cellprofiler -r -c -p /home/pstead/ExampleHumanImages/ExampleHuman.cppipe -o ExampleHumanImages/output/ -i /home/pstead/ExampleHumanImages/ --jvm-heap-size=1g -L 10
Version: 2014-11-04T15:34:33 2.1.1 / 20141104153433
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Uncaught exception in CellProfiler.py
Traceback (most recent call last):
  File "/hpf/tools/centos6/cellprofiler/2.1.1/src/CellProfiler/CellProfiler.py", line 251, in main
    run_pipeline_headless(options, args)
  File "/hpf/tools/centos6/cellprofiler/2.1.1/src/CellProfiler/CellProfiler.py", line 789, in run_pipeline_headless
    from cellprofiler.pipeline import Pipeline, EXIT_STATUS, M_PIPELINE
  File "/hpf/tools/centos6/cellprofiler/2.1.1/src/CellProfiler/cellprofiler/pipeline.py", line 58, in <module>
    from bioformats.omexml import OMEXML
  File "/hpf/tools/centos6/cellprofiler/2.1.1/src/CellProfiler/bioformats/__init__.py", line 20, in <module>
    import cellprofiler.utilities.jutil as jutil
  File "/hpf/tools/centos6/cellprofiler/2.1.1/src/CellProfiler/cellprofiler/utilities/jutil.py", line 100, in <module>
    ctypes.CDLL(os.path.join(jvm_dir, "libjvm.so"))
  File "/hpf/tools/centos6/cellprofiler/2.1.1/lib/python2.7/ctypes/__init__.py", line 353, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: Error occurred during initialization of VM
Could not reserve enough space for object heap/libjvm.so: cannot open shared object file: No such file or directory
Load ilastik Core
stopping worker thread  0
stopping worker thread  1
stopping worker thread  2
stopping worker thread  3
stopping worker thread  4
stopping worker thread  5
stopping worker thread  6
stopping worker thread  7
stopping worker thread  8
stopping worker thread  9
stopping worker thread  10
stopping worker thread  11
stopping worker thread  12
stopping worker thread  13
stopping worker thread  14
stopping worker thread  15
stopping worker thread  16
stopping worker thread  17
stopping worker thread  18
stopping worker thread  19
stopping worker thread  20
stopping worker thread  21
stopping worker thread  22
stopping worker thread  23
stopping worker thread  24
stopping worker thread  25
stopping worker thread  26
stopping worker thread  27
stopping worker thread  28
stopping worker thread  29
stopping worker thread  30
stopping worker thread  31
stopping worker thread  32
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Failed to stop the JVM

I cannot find a way to limit the number of worker threads or why so many are launched given the headless cp was supposed to be optimized for 1 core?

Any help would be welcomed!

Thanks,
Patrick

**Comment by dlogan** [comment] 2015-04-17 16:06
Yes, headless should only spawn a single thread.  Two things to note, though I am not sure they are the actual culprits here:

(1) Is the "cellprofiler" command you are submitting the compiled version?  This is troublesome in a cluster environment since you'd have to have compiled CP on each and every node.  We usually invoke CP with "python CellProfiler.py ..." as detailed [here](https://github.com/CellProfiler/CellProfiler/wiki#Running_CellProfiler_from_the_command_line) and further in the next section down on that page (LIMS).  Having said this, I'm not sure that using compiled here is forbidden and could in theory work?
(2) Also, this discussion might be of help: https://github.com/CellProfiler/CellProfiler/issues/1147
Namely, try using LoadData or even LoadImages rather than the Input Modules as shown in the GUI.  

David

**Comment by LeeKamentsky** [comment] 2015-04-17 16:27
It's Ilastik that's spawning all of the threads (and none of them are being used). I added a change (c3e226a12d3c1be7db1e7faac26a15eaaada87bc) that should limit Ilastik to one worker in headless. That's in the trunk build and will be in 2.1.2

**Comment by LeeKamentsky** [comment] 2015-04-22 12:49
Patrick, I'm going to close this one - you can open and comment if the problem isn't addressed. If you still are getting the high thread count, you can try defining the environment variable, "NUMBER_OF_PROCESSORS" to 1 and see if that helps.

**Closed by LeeKamentsky** 2015-04-22 12:49 UTC
