### ISSUE TITLE
Error while processing SaveImages

### ISSUE THREAD

**Issue by rachel662** [CellProfiler/CellProfiler#4359] opened 2021-02-19 19:52 UTC
Hi there 
I am trying to save images as a 16-bit integer in cellprofiler but I get an error saying 

"images of type float must be between -1 and 1"

I'm fairly new to image analysis so if anyone would be able to help me I'd be really grateful 

Cheers
Rachel

**Comment by bethac07** [comment] 2021-02-19 20:02
Hi,

You really do need to fill out the whole issue template, please don't just delete it, we really do need that information to help you; as we say in the template, reports without specification of OS/Version information or without SPECIFIC information on how to reproduce, including an attached/linked image set and pipeline, may be closed without investigation. I've reposted it here for your convenience.  

Alternately, if you're not sure if something is a bug but just looking for help using CellProfiler, forum.image.sc is the best place for that; you may also want to check out our [YouTube tutorials](https://www.youtube.com/playlist?list=PLXSm9cHbSZBBy7JkChB32_e3lURUcT3RL)


**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX 14.6]
 - CellProfiler Version [e.g. 2.2, 3.1.9]
 - Downloaded from the website or installed from source?
 - If the latter, how (cloned, installed from pypi, etc)?

**Additional context**
Add any other context about the problem here.

**Comment by rachel662** [comment] 2021-02-19 21:37
Hi, 
sorry about that, here is the template below 

Describe the bug
I am trying to save images as a 16-bit integer in cellprofiler but I get an error saying

"images of type float must be between -1 and 1"

I'm fairly new to image analysis so if anyone would be able to help me I'd be really grateful

Cheers
Rachel



To Reproduce
run the IMC segmentation pipeline 1_prepare_ilastik cellprofiler pipeline

See error: error in save images 
Expected behavior: images saved to ilastik output folder 


Screenshots
![image](https://user-images.githubusercontent.com/63318678/108564138-8a24f380-72fa-11eb-9af5-f5a0c546e004.png)


Desktop (please complete the following information):

OS:  Windows 10
CellProfiler Version: 4.1.3
Downloaded from the website 
Additional context: was using the IMC segmentation pipeline

**Comment by bethac07** [comment] 2021-02-19 21:49
We don't have that pipeline or the images to run it, you would need to attach/upload them as requested in order for us to fully troubleshoot this.  In general, though, CellProfiler will not allow images whose values are outside -1 to 1 to be saved as TIFFs, as is documented in the module help.  I'm not sure why your pipeline is producing values outside that range, since you're using a number of custom plugins not in our standard plugin library, so you should use the help on those plugins or consult with the person who wrote them; if you want to enforce the images being in the 0-to-1 range, you can do so with either the RescaleIntensity or ImageMath modules, but I can't say for sure which is more appropriate (or if it means something is wrong in the earlier plugin steps) with the information I currently have.

Closing here as this isn't a CellProfiler bug, you are welcome to make a thread on forum.image.sc if you are still having trouble after you consult with the plugin creators.

**Closed by bethac07** 2021-02-19 21:49 UTC
Labels: Bug, Needs verification
