### ISSUE TITLE
Problem with opening TIF files from Operetta with CellProfiler 5.0.01b

### ISSUE THREAD

**Issue by wichaidi** [CellProfiler/CellProfiler#4937] opened 2024-08-23 20:39 UTC
Hi -

I got an error after trying to open the image (double clicked). 

![2024-08-21 15_35_20-CP_openFileError](https://github.com/user-attachments/assets/e73859e3-7460-4707-a56a-424a040d382d) 

```
Traceback (most recent call last):
  File "ImageReader.java", line 863, in loci.formats.ImageReader.setId
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xxxxxxxx\Documents\GitHub\CellProfiler\cellprofiler\gui\utilities\figure.py", line 148, in show_image
    image = provider.provide_image(None).pixel_data
  File "C:\Users\xxxxxxxx\Documents\GitHub\CellProfiler\core\cellprofiler_core\image\abstract_image\file\_file_image.py", line 377, in provide_image
    self.__set_image()
  File "C:\Users\xxxxxxxx\Documents\GitHub\CellProfiler\core\cellprofiler_core\image\abstract_image\file\_file_image.py", line 324, in __set_image
    img, self.scale = rdr.read(
  File "C:\Users\xxxxxxxx\Documents\GitHub\CellProfiler\core\cellprofiler_core\readers\bioformats_reader.py", line 84, in read
    self._ensure_file_open()
  File "C:\Users\xxxxxxxx\Documents\GitHub\CellProfiler\core\cellprofiler_core\readers\bioformats_reader.py", line 54, in _ensure_file_open
    self.get_reader().setId(self.file.path)
loci.formats.loci.formats.FormatException: loci.formats.FormatException: Could not find XML file C:\Users\xxxxxxxx\Downloads\HFFs_2dpi_WT_JT_072324__2024-07-23T14_24_07-Measurement 1\Images\Index.idx.xml

```
The tiff image is posted [here](https://data.cyverse.org/dav-anon/iplant/home/wichaidi/public/r06c02f43p01-ch2sk1fk1fl1.tiff
)

Please let me know if you need more info

Thank you,
Pearl

**System Config**
I use Windows11 version 22H2
CellProfiler 5.0.0b1 installed from source with CellPose. 
my environment file can be found [here](https://data.cyverse.org/dav-anon/iplant/home/wichaidi/public/environment.yml
)  

**Additional Info**
 I have all the CellProfiler Image Readers enabled as suggested on the Image Forum but still didn't help. The person on the forum mentioned that he tried on 4.2.6 and 4.2.7 and he could open the image. 

I successfully opened the image by dragging and dropping on FIJI. However when I used Bio-Format importer it gave an error in loci.formats.in.OperettaReader.initFile(OperettaReader.java:303)

**Comment by wichaidi** [comment] 2024-08-28 17:17
I would like to add that [Esteban Miglietta](https://forum.image.sc/u/Esteban_Miglietta) helped me figuring out how to opened the tiff files as posted [here](https://forum.image.sc/t/problem-with-opening-tif-files-from-operetta/100746/12?u=pearl_wichaidit). There is an xml file that comes along with the tiffs from Operetta. Below is Esteban's solution:

With ImageIO tiff reader disabled and Bioformats enabled, I tired:

1. Opening the tiff file directly: I met the same error as you
2. Renaming the Index.xml file you provided as ‘Index.idx.xml’: the image opened but it was all zeros
3. Deleting the .xml file or renaming it something completely different (either the name OR the extension): THE IMAGE OPENED JUST FINE!! :dizzy_face:

Hope this info helps with the next stable release. Thanks,
Pearl

**Comment by gnodar01** [comment] 2024-08-28 21:54
Yes, when Esteban showed that to me I was definitely surprised. 

This seems to be some kind of bug with the `OperettaReader` of the `BioFormats` library.

There is some hardcoded list where both of those file names are mentioned, [here](https://github.com/ome/bioformats/blob/develop/components/formats-gpl/src/loci/formats/in/OperettaReader.java#L69).

You can for example get the same error when opening your file in Fiji via `File -> Import -> Bio-Formats`:

<img width="857" alt="Screenshot 2024-08-28 at 5 48 56 PM" src="https://github.com/user-attachments/assets/690c6d49-fb10-495e-88f3-f7ec522855e5">

This is only speculation, but alternatively it is a "feature" and not a bug of that reader, and when using that reader you are supposed to provide a differently structured `.xml` file than the one you have. When you remove the file, and it does not find it, it may instead trigger a more simple `tiff` reader which successfully opens your image.

In any case I will close this issue, since there is nothing to be done on the part of CellProfiler. Feel free to post an issue on the [bio-formats](https://github.com/ome/bioformats) repo if you feel it will be helpful.

Thanks for reporting!

**Closed by gnodar01** 2024-08-28 21:54 UTC
Labels: Bug, Needs verification
