### ISSUE TITLE
NamesAndTypes - load objects and illum functions even if All Images is chosen 

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2358] opened 2016-09-22 17:44 UTC
Currently, if NamesAndTypes is set to "All Images", the 'Select the image type' dropdown shows 3 choices:
- Grayscale
- Color
- Binary

If however you choose "Images matching rules", the 'Select the image type' dropdown shows 5 choices:
- Grayscale
- Color
- Binary
- Objects
- Illum functions

Now, strictly speaking this is pretty sensible because it's unlikely anyone would ever have a pipeline consisting entirely of Illum functions or objects, with no other accompanying images. However, it's confusing when you go looking for a way to load images as objects and you don't see that option as even being possible. 

There is work underway to offer more clear options in NamesAndTypes (2D vs 3D, time-lapse vs not, grayscale vs not). Therefore, it would make sense to show these choices in a parallel way (objects or not, illum functions or not, binary or not) regardless of whether "All Images" or "Images matching rules" is selected.

**Comment by mcquin** [comment] 2017-04-21 17:45
Duplicate of https://github.com/CellProfiler/CellProfiler/issues/1992

**Closed by mcquin** 2017-04-21 17:45 UTC
Labels: Enhancement
