### ISSUE TITLE
CellProfiler icons missing in Start menu for beta 2.2.0

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1826] opened 2016-03-09 19:44 UTC
![image](https://cloud.githubusercontent.com/assets/1225595/13648148/42d2638c-e605-11e5-8e3c-37979d45d816.png)

**Comment by mcquin** [comment] 2017-04-13 21:28
Possible duplicate of/can be bundled with #2686

**Closed by mcquin** 2017-04-13 21:28 UTC
