### ISSUE TITLE
SaveImages java exception and assertion errors

### ISSUE THREAD

**Issue by derekthirstrup** [CellProfiler/CellProfiler#2163] opened 2016-07-22 23:14 UTC
I am using the SaveImages module to write out object tracking labeled images from an upstream object tracking module.  I had two other object tracking modules already in the pipeline without an issue.  This bug started to occur after I added the third object tracking module with its associated SaveImages module.  The assertion bug occurs if I write back to the image folder. Now the java exception comes up if writing the SaveImages module image to the output folder.  This java exception warning message stops the pipeline execution run until the dialog button "continue processing" is clicked.  Is there a limit on the number of SaveImages modules that can be used in a pipeline?  

![saveimages module java exception](https://cloud.githubusercontent.com/assets/20077409/17073402/7ae627ec-5025-11e6-85d3-5c1d723c6521.jpg)

![saveimages module assertion error](https://cloud.githubusercontent.com/assets/20077409/17073546/9bda72f4-5026-11e6-8ff9-9abf036dbd6a.jpg)

**Comment by braymp** [comment] 2016-07-23 10:32
No, there should not be any limit on the # of SaveImages modules allowed.

There are several SavesImages/JavaException issues already filed. Without seeing the exception itself, it's hard to know the source. You may want to post your pipeline to this thread.

Assertion error: Duplicate of #1325.

**Comment by derekthirstrup** [comment] 2016-07-25 22:39
Hi Mark,

Here is a pipeline that displays the assertion error which apparently prevents the SaveImages module from saving any images to the output folder.  It appears to skip the save images module if one clicks yes to the warning box since no output images are written to disk.  This pipeline is a work around till we have the ability to encode the object tracking label as an indexed grayscale value that matches the tracking label number which is currently broken by a matplotlib resize bug in the display data on image module.


[Pipeline&ShortImageList.zip](https://github.com/CellProfiler/CellProfiler/files/382619/Pipeline.ShortImageList.zip)

**Closed** 2020-02-13 21:20 UTC
Labels: Needs verification
