### ISSUE TITLE
GUI does not appear until clicking the icon in the dock on Mac OS 10.10.5

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#1821] opened 2016-03-08 03:35 UTC
Using today's beta (CP 2.2.0rc2 (rev e5117de)), I doubleclick the app and wait, and wait, and wait. If I click the icon in the dock the GUI appears.

**Comment by dlogan** [comment] 2016-03-08 14:52
Related to https://github.com/CellProfiler/CellProfiler-Analyst/issues/170 ?

**Comment by LeeKamentsky** [comment] 2016-03-08 14:54
Most likely, it just needs a call to Frame.Raise somewhere in CellProfilerApp.py.

**Comment by daviddao** [comment] 2016-03-08 15:32
Maybe it is because of our automatic mac build machine. I don't experience this in windows or on builds using my machine. CP and CPA are automatically build on the same Mac.

**Comment by dlogan** [comment] 2016-03-09 19:39
Duplicate of #1738

**Closed** 2016-03-09 21:55 UTC

**Comment by dlogan** [comment] 2016-03-10 03:49
Is this fixed?  Does the fix also apply to https://github.com/CellProfiler/CellProfiler-Analyst/issues/170?
