### ISSUE TITLE
CP crash on Mac compiled release version

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1342] opened 2015-04-16 14:18 UTC
[This Forum user](http://cellprofiler.org/forum/viewtopic.php?f=14&t=4263&sid=90b9e78844f83a2564f4b1d00eec0c11) cannot get CP to run on his Mac.  They have tried all the usual fixes, i.e. removing config files.  Crash log is attached.  Java 1.6

Attachments:
http://cellprofiler.org/issues/uploaded/fdIaCh/CellProfiler_2015-04-13-120958_a180-mac8.crash

**Comment by LeeKamentsky** [comment] 2015-04-16 20:00
It's crashing in libfreetype - maybe there's something corrupted in that. I don't know if you can look at the crash dump and tell whether you have libfreetype.so.6 as the standard one on a Mac. I'll look at it in more depth when I get back.

**Comment by dlogan** [comment] 2015-04-17 18:02
On my Mac (which is not crashing), I have libfreetype.6.dylib in /Users/dlogan/github/CPhomebrew/Cellar/freetype/2.5.2/lib/libfreetype.6.dylib
and 
/opt/X11/lib/libfreetype.6.dylib

So I think that is just the Mac branded version on the .so.6 file, no?

**Comment by LeeKamentsky** [comment] 2015-04-18 12:10
I just looked again - libfreetype.6.dylib is the one distributed with CellProfiler, so it's still a mystery why it's crashing.

**Comment by dlogan** [comment] 2015-04-18 12:57
seems odd, but maybe this helps?  Is it possible that particular fonts have to be supplied as well as libfreetype?
http://stackoverflow.com/questions/19375796/mac-os-x-archive-app-crashed-on-test-mac-machine-exc-bad-instruction

**Comment by LeeKamentsky** [comment] 2015-04-18 16:30
Thanks David. That's almost certainly it. I am betting that they had set their default font to something other than the installed default in 2.0 and when the preferences format changed, it mangled the path. Could you have them try deleting their preferences?

**Comment by dlogan** [comment] 2015-04-21 00:39
They said they had done deleted their preferences, but I asked then again to do it, but to also:
(1) Uninstall CP (all versions!)
(2) Delete the file ~/Library/Preferences/CellProfilerLocal.cfg
(3) Empty your Mac Trash

We'll see if that helps.

**Comment by dlogan** [comment] 2015-04-21 13:34
Removing preferences didn't work for them.  
```
I did the uninstall, delete .cfg, empty trash, reinstall again, and still doesn't work. And I didn't change any default font or anything in 2.0. 
```
I asked for the most recent crash log.  Other thoughts?

**Comment by dlogan** [comment] 2015-04-22 12:50
The user sent another crashlog, but it appears to me to be the same underlying issue.  Not sure why they still get this after they supposedly removed the preferences. 

Crashlog link:
http://cl.ly/3h472m2E171p

**Comment by dlogan** [comment] 2015-04-27 14:42
This is the only location for CP Mac prefs, right?
~/Library/Preferences/CellProfilerLocal.cfg

**Comment by LeeKamentsky** [comment] 2015-04-27 15:33
I am not sure if there is another place for the preferences. There may be another problem and the preferences may not be the cause. The following post has a similar stack trace:
http://matplotlib.1069221.n5.nabble.com/Bus-error-when-importing-from-matplotlib-td23498.html

The build machine has freetype 2.5.2 - possibly upgrading to 2.5.5 or later can help. I will try doing that and then the user can try the trunk build and see if the problem is fixed.

**Comment by LeeKamentsky** [comment] 2015-04-27 20:35
The build has been done - I'd appreciate it if the user could try the current trunk build.

**Comment by dlogan** [comment] 2015-04-27 21:32
Thanks - I requested.

**Comment by dlogan** [comment] 2015-06-29 17:55
The user reported (back in April, sorry) that this did not work for them.  Their crash log is here: http://cellprofiler.org/forum/viewtopic.php?f=14&t=4263&sid=90b9e78844f83a2564f4b1d00eec0c11#p12968

In addition, [another user](http://www.cellprofiler.org/forum/viewtopic.php?f=14&t=4398&hilit=glyph) has what appears to be a font issue as well, this time on Windows.

**Comment by LeeKamentsky** [comment] 2015-06-30 20:01
I am grasping at straws but it might be that the Matplotlib fonts are not there. I think the one that gets loaded first should be at /Applications/CellProfiler.app/Contents/Resources/mpl-data/fonts/ttf/Vera.ttf

I'd check to see if that file is somehow funky - no read permissions, doesn't display the font when you bring it up using Finder and GetInfo.

**Comment by LeeKamentsky** [comment] 2015-06-30 20:10
The Windows issue is totally different. I replied. If the user says it's not fixed, it should be its own bug.

**Comment by braymp** [comment] 2016-01-22 20:09
Closing; re-open if it crops up again.

**Closed by braymp** 2016-01-22 20:09 UTC
Labels: Bug
