### ISSUE TITLE
Metadata: Problem with file metadata updating

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1102] opened 2014-04-08 13:45 UTC
From http://cellprofiler.org/forum/viewtopic.php?f=16&t=3741

A user reports the following error using the release on the attached project file:
```
Traceback (most recent call last):
File "cellprofiler\gui\moduleview.pyc", line 1102, in callback
File "cellprofiler\gui\moduleview.pyc", line 1976, in __on_do_something
File "cellprofiler\settings.pyc", line 1923, in on_event_fired
File "cellprofiler\modules\metadata.pyc", line 484, in <lambda>
File "cellprofiler\modules\metadata.pyc", line 824, in do_update_metadata
File "cellprofiler\utilities\hdf5_dict.pyc", line 1304, in add_metadata
TypeError: 'NoneType' object is not iterable
```
I provided a new project with the following fix (which worked for me):
* NamesAndTypes: Under "Image set matching method", select "Metadata" and select "FileLocation" for all 4 channels.
* Groups: Enable grouping, and select "FileLocation" as the metadata.
However, this only worked as long as they didn't change the input directory; the error reoccurred when the files were moved elsewhere. It also occurred if they cleared the Images File List and re-added them.

Attachments:
http://cellprofiler.org/issues/uploaded/yjEZ0H/issue.cpproj

**Comment by AnneCarpenter** [comment] 2016-09-02 11:52
Closing, feel free to re-open if the problem is verified and still exists.

**Closed by AnneCarpenter** 2016-09-02 11:52 UTC
Labels: Bug, User-requested
