### ISSUE TITLE
IdentifyObjectsManually wx error

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2443] opened 2016-11-08 18:46 UTC
When using IdentifyObjectsManually in ~2.4 or later (bug not present in Stable, is in the May nightly and running from source on master), you get the following error:

```Traceback (most recent call last):
  File "I:\GitHub\CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 2844, in do_step
    self.__pipeline.run_module(module, workspace)
  File "I:\GitHub\CellProfiler\cellprofiler\pipeline.py", line 2108, in run_module
    module.run(workspace)
  File "I:\GitHub\CellProfiler\cellprofiler\modules\identifyobjectsmanually.py", line 83, in run
    self, pixel_data, workspace.measurements.image_set_number)
  File "I:\GitHub\CellProfiler\cellprofiler\workspace.py", line 349, in interaction_request
    return module.handle_interaction(*args, **kwargs)
  File "I:\GitHub\CellProfiler\cellprofiler\modules\identifyobjectsmanually.py", line 181, in handle_interaction
    title) as dialog_box:
  File "I:\GitHub\CellProfiler\cellprofiler\gui\editobjectsdlg.py", line 143, in __init__
    self.build_ui()
  File "I:\GitHub\CellProfiler\cellprofiler\gui\editobjectsdlg.py", line 272, in build_ui
    self.toolbar = cellprofiler.gui.figure.CPNavigationToolbar(self.panel)
  File "C:\Users\bcimini\AppData\Local\Continuum\Anaconda2\lib\site-packages\matplotlib\backends\backend_wx.py", line 1572, in __init__
    wx.ToolBar.__init__(self, canvas.GetParent(), -1)
  File "C:\Users\bcimini\AppData\Local\Continuum\Anaconda2\lib\site-packages\wx-3.0-msw\wx\_core.py", line 10271, in GetParent
    return _core_.Window_GetParent(*args, **kwargs)
TypeError: in method 'Window_GetParent', expected argument 1 of type 'wxWindow const *'
```

**Comment by Fafa87** [comment] 2017-05-11 06:43
Hi!
The problem is that CanvasPatch(matplotlib.backends.backend_wxagg.FigureCanvasWxAgg) is not properly initialized. Error was introduced in some sort of cleaning sweep:
- missing __init__ (2d234c0a2d67150117d21811245136a6cb043d26)
    added __init__ that did not call base (FigureCanvasWxAgg) constructor
- deleted unexpected arguments (9fb1a59395adf0f25ca026d5007feae1e2114faf)
    vital arguments deleted

I fixed it in my sstoma-yit branch as editobjectsdlg is used in cellstar parameter search. You can wait for PR of the branch or cherry-pick it if needed:
https://github.com/Fafa87/CellProfiler/commit/52cde2321b386049d5203999f7eaaaae77800307

I've just noticed that the rest of the added __init__ were then removed. So removing __init__ altogether (base is then used) might be a more consistent solution.

**Comment by Fafa87** [comment] 2017-05-22 20:48
Fixed by a dedicated PR https://github.com/CellProfiler/CellProfiler/pull/2779

**Closed** 2017-05-30 15:46 UTC
Labels: Bug
