### ISSUE TITLE
Upgrade to wxPython-Phoenix

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2040] opened 2016-05-18 22:40 UTC

**Comment by omsai** [comment] 2016-12-28 01:50
pypi's listing for wxpython does not support GNU/Linux meaning one has to use the newer wxpython-phoenix on that platform.
Can anyone reproduce this error with python 2.7.6 and wxpython-phoenix==3.0.3?

```pytb
Traceback (most recent call last):
  File "/apps2/python/2.7.6-gcc/bin/cellprofiler", line 11, in <module>
    load_entry_point('CellProfiler', 'console_scripts', 'cellprofiler')()
  File "/shared/admin/sw-src/rhel6/cellprofiler/2.2.0/cellprofiler-2.2.0/cellprofiler/__main__.py", line 176, in main
    cp_start_vm()
  File "/shared/admin/sw-src/rhel6/cellprofiler/2.2.0/cellprofiler-2.2.0/cellprofiler/utilities/cpjvm.py", line 153, in cp_start_vm
    class_path = get_jars()
  File "/shared/admin/sw-src/rhel6/cellprofiler/2.2.0/cellprofiler-2.2.0/cellprofiler/utilities/cpjvm.py", line 73, in get_jars
    plugin_directory = cpprefs.get_ij_plugin_directory()
  File "/shared/admin/sw-src/rhel6/cellprofiler/2.2.0/cellprofiler-2.2.0/cellprofiler/preferences.py", line 832, in get_ij_plugin_directory
    if config_exists(IJ_PLUGIN_DIRECTORY):
  File "/shared/admin/sw-src/rhel6/cellprofiler/2.2.0/cellprofiler-2.2.0/cellprofiler/preferences.py", line 221, in config_exists
    if not get_config().Exists(key):
  File "/shared/admin/sw-src/rhel6/cellprofiler/2.2.0/cellprofiler-2.2.0/cellprofiler/preferences.py", line 109, in get_config
    wx.Config.Set(wx.Config('CellProfiler','BroadInstitute','CellProfilerLocal.cfg','CellProfilerGlobal.cfg',wx.CONFIG_USE_LOCAL_FILE))
AttributeError: 'module' object has no attribute 'CONFIG_USE_LOCAL_FILE'
```

The older wxpython is still in package managers, but that solution is not feasible for an HPC cluster.

Command that created the above traceback:

```sh
$ cellprofiler --pipeline=/scratch/scratch3/pan14001/pipeline.cpproj \
               --output-directory=/work/pan14001 \
               --image-directory=/work/pan14001/z_stack \
               --done-file=/work/pan14001/status
```

Installed packages

```sh
$ pip list --format=columns
Package                            Version     Location                                                        
---------------------------------- ----------- ----------------------------------------------------------------
alabaster                          0.7.9       
amqp                               1.4.9       
Angel                              1.0         
anyjson                            0.3.3       
appdirs                            1.4.0       
astroid                            1.4.9       
atomicfile                         1.0         
avro                               1.7.7       
Babel                              2.3.4       
backports-abc                      0.4         
backports.functools-lru-cache      1.3         
backports.shutil-get-terminal-size 1.0.0       
backports.ssl-match-hostname       3.4.0.2     
bcbio-gff                          0.6.2       
billiard                           3.3.0.23    
biom-format                        2.1.5       
biopython                          1.67        
burrito                            0.9.1       
burrito-fillings                   0.1.1       
celery                             3.1.23      
cellh5                             1.3.0       
CellProfiler                       2.2.0       /shared/admin/sw-src/rhel6/cellprofiler/2.2.0/cellprofiler-2.2.0
centrosome                         1.0.5       
certifi                            2016.9.26   
CIRCexplorer                       1.1.10      
click                              6.6         
cogent                             1.5.3       
configparser                       3.5.0       
ConsensusCore                      1.0.1       
ConsensusCore2                     0.9.0       
custodian                          0.8.1       
Cython                             0.24        
dask                               0.11.1      
decorator                          4.0.10      
docopt                             0.6.2       
docutils                           0.12        
emperor                            0.9.51      
entrypoints                        0.2.2       
enum34                             1.1.6       
ete2                               2.2.1072    
fastcluster                        1.1.13      
funcsigs                           1.0.2       
functools32                        3.2.3.post2 
future                             0.15.2      
gdata                              2.0.18      
GenomicConsensus                   2.0.0       
greenlet                           0.4.9       
GridDataFormats                    0.2.4       
h5py                               2.6.0       
hmmlearn                           0.2.0       
Hop                                0.3.4       
humann2                            0.6.0       
imagesize                          0.7.1       
imbalanced-learn                   0.1.8       
inflect                            0.2.5       
ipykernel                          4.5.0       
ipython                            4.2.1       
ipython-genutils                   0.1.0       
ipywidgets                         5.2.2       
isort                              4.2.5       
javabridge                         1.0.14      
Jinja2                             2.8         
jsonschema                         2.5.1       
jupyter-client                     4.4.0       
jupyter-core                       4.2.0       
keyring                            5.6         
kneaddata                          0.5.1       
kombu                              3.0.35      
lazy-object-proxy                  1.2.2       
leveldb                            0.193       
libtiff                            0.4.0       
lxml                               3.4.2       
Mako                               1.0.4       
MarkupSafe                         0.23        
MAST                               1.2.9.4     
matplotlib                         1.3.1       
mccabe                             0.5.3       
MDAnalysis                         0.8.1       
mdtraj                             1.7.2       
MIDAS                              1.2.0       
misopy                             0.5.2       
mistune                            0.7.3       
mock                               2.0.0       
monty                              0.6.4       
mpi4py                             2.0.0       
msmbuilder                         3.5.0       
mysql                              0.0.1       
MySQL-python                       1.2.5       
natsort                            3.5.6       
nbconvert                          4.2.0       
nbformat                           4.1.0       
netCDF4                            1.2.4       
networkx                           1.11        
nose                               1.3.3       
notebook                           4.2.3       
numexpr                            2.3.1       
numpy                              1.11.3      
numpydoc                           0.6.0       
OpenMM                             7.0.1       
pandas                             0.19.1      
pathlib2                           2.1.0       
pbalign                            0.2.0       
pbcommand                          0.2.17      
pbcore                             1.2.6       
pbh5tools                          0.8.0       
pbr                                1.10.0      
pexpect                            4.2.1       
phonopy                            1.10.10     
pickleshare                        0.7.4       
PIL                                1.1.7       
Pillow                             3.4.2       
pip                                9.0.1       
prettytable                        0.7.2       
prokaryote                         1.0.11      
prompt-toolkit                     1.0.9       
protobuf                           3.0.0b2     
PseudoNetCDF                       2.0         
ptyprocess                         0.5.1       
py                                 1.4.28      
pybtex                             0.18        
pycuda                             2015.1      
Pygments                           2.1.3       
pyhull                             1.5.4       
pylint                             1.6.4       
pymatgen                           3.0.13      
PyMySQL                            0.6.7       
pynast                             1.2.2       
pyparsing                          2.0.2       
pyproj                             1.9.3       
pyqi                               0.3.2       
pysam                              0.8.1       
pytest                             2.7.1       
python-bioformats                  1.1.0       
python-dateutil                    2.5.3       
python-gflags                      3.0.4       
pytools                            2014.3.5    
pytz                               2016.7      
PyYAML                             3.10        
pyzmq                              15.2.0      
qcli                               0.1.1       
qiime                              1.9.1       
qiime-default-reference            0.1.3       
requests                           2.6.0       
Rtree                              0.8.2       
scikit-bio                         0.2.3       
scikit-image                       0.12.3      
scikit-learn                       0.17.1      
scipy                              0.18.1      
scoop                              0.7.1.1     
seaborn                            0.7.1       
setuptools                         28.8.0      
Shapely                            1.5.13      
simplegeneric                      0.8.1       
singledispatch                     3.4.0.3     
six                                1.10.0      
snowballstemmer                    1.2.1       
Sphinx                             1.4.5       
tables                             3.1.0       
tensorflow                         0.10.0rc0   
terminado                          0.6         
tflearn                            0.2.1       
Theano                             0.8.1       
toolz                              0.8.0       
tornado                            4.4.2       
traitlets                          4.3.1       
verlib                             0.1         
virtualenv                         15.0.2      
wcwidth                            0.1.7       
wheel                              0.29.0      
widgetsnbextension                 1.2.6       
wrapt                              1.10.8      
wxPython-Phoenix                   3.0.3       
xgboost                            0.6         
xmlbuilder                         1.0         
yamltools                          0.1      
```

**Comment by mcquin** [comment] 2017-01-06 22:29
Duplicate of #2536

**Closed by mcquin** 2017-01-06 22:29 UTC
