### ISSUE TITLE
Workspace Viewer: Crash terminates CP expectedly

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#2748] opened 2017-05-04 13:12 UTC
Hopefully, this is reproducible: 
* Load the attached pipeline and images
* Start test mode, and run the pipeline to the end
* Start the Workspace Viewer (WSV) and adjust the settings to the following (do it in this order):
  * Images: DAPI and FITC
  * Objects: Nuclei and Myotubes
* Now, enable the "Show" checkboxes next to each of these, in the same order

Upon enabling the Myotubes checkbox, CP dies a horrible death. No stack trace is produced upon termination.
[issue.zip](https://github.com/CellProfiler/CellProfiler/files/976200/issue.zip)

**Comment by 0x00b1** [comment] 2017-05-04 16:40
Hi, @braymp, I couldn’t reproduce on macOS (10.11.6) and latest CellProfiler. What version of CellProfiler are you using? What operating system?

**Comment by braymp** [comment] 2017-05-04 17:36
I'm using 2.2.0 (ac0529e) on a Windows 7 64-bit machine.

**Comment by ehmanna** [comment] 2019-09-25 07:23
Hi @braymp, did you ever work out a fix for this issue? I'm having similar trouble with displaying (any) secondary objects in the WSV - primary objects are shown with no problems but enabling the checkbox for secondary objects crashes CP immediately.

**Comment by braymp** [comment] 2019-09-25 12:16
No, I never did. I have noticed that it would crash for some objects in a test run but not others, but never took the time to figure what sort of objects caused that behavior. So it's interesting if a secondary object-specific failure...

**Closed** 2020-03-24 20:18 UTC
Labels: Needs verification

**Comment by jmonda** [comment] 2022-10-13 00:26
I am having this same issue on CP 4.2.4. My pipeline successfully runs, but when I try to view the images/analysis in workspace, CP crashes. I am able to display my images and primary objects. However when I try to display my secondary or filtered objects, CP immediately crashes. Any advice would be greatly appreciated!

**Comment by braymp** [comment] 2022-10-13 01:12
No advice from me; it still occurs occasionally. Interesting if it really is a filtered/secondary object issue, though.

**Comment by jmonda** [comment] 2022-10-13 18:27
It also seems to be only specific images that are problematic. Most are ok, but other images collected and processed identically consistently fail in workspace, even across multiple computers.
Sorry to hear you still experience the issue as well Mark, but I appreciate the response.
