### ISSUE TITLE
[Ubuntu 16.04] Zoom and navigate buttons not shown

### ISSUE THREAD

**Issue by minh-doan** [CellProfiler/CellProfiler#3103] opened 2017-09-12 17:13 UTC
For all the result windows (IdentifyPrimaryObjects, FilterObjects etc...)
<img width="893" alt="screen shot 2017-09-12 at 12 48 53 pm" src="https://user-images.githubusercontent.com/22305129/30339174-2def84b2-97bc-11e7-8477-13c4c80fe9ea.png">

**Comment by bethac07** [comment] 2017-09-12 17:20
Duplicate of #2679

**Comment by mcquin** [comment] 2017-09-12 18:21
Closed as duplicate.

**Closed by mcquin** 2017-09-12 18:21 UTC
