### ISSUE TITLE
Wx errors using 'EditObjectsManually' 

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2677] opened 2017-03-31 19:46 UTC
[From this forum post](http://forum.cellprofiler.org/t/cellprofiler-crashes-using-editobjectsmanually/4529), a Linux CP users says he can only edit two objects in EditObjectsManually before running into the following error:
```
Traceback (most recent call last):
File "/home/mplace/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_wx.py", line 1041, in _onRightButtonDown
self.CaptureMouse()
File "/home/mplace/anaconda/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 10641, in CaptureMouse
return core.Window_CaptureMouse(*args, **kwargs)
PyAssertionError: C++ assertion "!wxMouseCapture::IsInCaptureStack(this)" failed at ./src/common/wincmn.cpp(3271) in CaptureMouse(): Recapturing the mouse in the same window?
```

I have asked him to follow the issue over here in case you guys have questions re: CP version, WX version(s), etc.

**Comment by wiscplace** [comment] 2017-03-31 20:07
Name: wxPython
Version: 3.0.0.0

CellProfiler version 2.2.0 (rev ac0529e)

**Comment by wiscplace** [comment] 2017-05-03 18:56
Progress Counter({u'FinishedWaitingMeasurements': 1})
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fc5a9bb8d07, pid=7525, tid=0x00007fc5bd3f7740
#
# JRE version: OpenJDK Runtime Environment (8.0_102-b14) (build 1.8.0_102-b14)
# Java VM: OpenJDK 64-Bit Server VM (25.102-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libwx_gtk2u-3.0.so.0+0x85bd07]  wxWindowBase::ReleaseMouse()+0x66b
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/mplace/projects/image_overlap/Compare_masson_mcclean_scopes/masson/hs_err_pid7525.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)

**Comment by AetherUnbound** [comment] 2018-01-04 01:50
Is there a set of images/pipeline for reproducing this issue?

**Comment by AetherUnbound** [comment] 2018-01-04 01:57
FWIW I am not able to reproduce this issue in CP 3

**Comment by AetherUnbound** [comment] 2018-01-04 16:08
As this is not a critical issue and it is absent in CP 3, I'm going to close this issue.

**Closed by AetherUnbound** 2018-01-04 16:08 UTC
Labels: Needs verification
