### ISSUE TITLE
EditObjectsManually init error

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2789] opened 2017-06-09 13:46 UTC
From [the forum](http://forum.cellprofiler.org/t/editobjectsmanually--init--error/4785):

`
Hello,
When I try to use the module EditObjectsManually after IdentifyPrimaryObjects, it returns with the following error:
`
```
Traceback (most recent call last):
File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/gui/pipelinecontroller.py", line 2839, in do_step
File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/pipeline.py", line 2089, in run_module
File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/modules/editobjectsmanually.py", line 195, in run
File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/workspace.py", line 353, in interaction_request
File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/modules/editobjectsmanually.py", line 441, in handle_interaction
File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/gui/editobjectsdlg.py", line 143, in init
File "/Applications/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/gui/editobjectsdlg.py", line 271, in build_ui
TypeError: init() takes exactly 1 argument (4 given)
```
`
Only the error window opens, no processing window where I can edit the objects. Any ideas? Thanks for the help! 
`
`
I am on a macbook pro running OSX 10.12.14 and using CP 2.2.0rc3
`

Nothing obviously wrong in his pipeline settings; I tried to reproduce but could not, though it could be a Mac/PC thing. His image and pipeline are attached.

[WormAnalyzerNew_small_sizemeasure2.zip](https://github.com/CellProfiler/CellProfiler/files/1064197/WormAnalyzerNew_small_sizemeasure2.zip)

**Comment by 0x00b1** [comment] 2017-06-09 16:19
Weird bug. I'll need to investigate.

**Comment by AetherUnbound** [comment] 2018-01-07 03:42
I cannot reproduce this issue in CP 3 for Ubuntu 16.04. @0x00b1, were you able to reproduce this?

**Comment by mcquin** [comment] 2018-01-09 14:45
Unable to reproduce on OS X.

Closing due to lack of reproducibility.

**Closed by mcquin** 2018-01-09 14:45 UTC
Labels: Needs verification
