### ISSUE TITLE
Make GUI help windows print-able

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2905] opened 2017-08-30 14:05 UTC
Would certainly be useful for us as we do documentation review to be able to print (or PDF) these. 

It's a nice option for users in general though I'm not going to claim it's super important.

If this ends up being a >15 minute thing then forget about it!

**Comment by mcquin** [comment] 2017-08-30 14:21
Duplicate of https://github.com/CellProfiler/CellProfiler/issues/2592

**Closed by mcquin** 2017-08-30 14:21 UTC
