### ISSUE TITLE
CP 4.07 3D image stack 

### ISSUE THREAD

**Issue by TeamPrigge** [CellProfiler/CellProfiler#4344] opened 2021-02-06 14:41 UTC
the 3D images segmentation and processing is all buggy and most of the modules are showing Error"NonType object has no attribute Check" which you have to disable figure desplay which makes no sense if one does it for many modules. Even in the images everything is desplayed as 2D with the disability to right click and change anything. I was wondering until when we have to wait for the problem to be fixed.
Thanks

**Comment by DavidStirling** [comment] 2021-02-08 17:55
This is a duplicate of #4337, and shall be fixed in the next release. Thanks

**Closed by DavidStirling** 2021-02-08 17:55 UTC
