### ISSUE TITLE
ExportToDatabase with SQLite and per-well aggregation produces empty tables

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1340] opened 2015-04-13 19:28 UTC
[This Forum user](http://cellprofiler.org/forum/viewtopic.php?f=16&t=4249&sid=de8a21cd7ed7db3285c0f17fd962efb4) pointed out that ExportToDatabase with SQLite and per-well aggregation produces empty database tables.  The cpproj file and sample images are in the Forum.  If you turn off the per-well aggregation in ExportToDatabase, the produced table(s) at least have data in them.  (Note that the error appears in CPA, however it is because the CP-produced image and object tables are empty)

Related to #112, but that issue implies that the settings do not exist for per-well aggregation.  Indeed they do exist for sqlite, however they don't produce the correct output.

**Comment by LeeKamentsky** [comment] 2015-04-14 13:49
ExportToDatabase is silently eating an exception (which I will now change). The width of the per-image table is 1923 columns and that is close to the limit of 2000 columns (http://www.sqlite.org/limits.html). The actual error is "too many SQL variables" and is caused by the way I issue SQL insert statements. 

BTW @AnneCarpenter, this would be solved by an RDF schema. CP's long column format has always been one of my bugbears and not just mine - this is from the SQLite developers, in their comments on limits:

> The default setting for SQLITE_MAX_COLUMN is 2000. You can change it at compile time to values as large as 32767. On the other hand, many experienced database designers will argue that a well-normalized database will never need more than 100 columns in a table.

**Comment by AnneCarpenter** [comment] 2015-04-15 13:21
Noted!

**Comment by braymp** [comment] 2016-01-22 20:11
Closing since Lee addressed the original issue.

**Closed by braymp** 2016-01-22 20:11 UTC
Labels: Bug, Output-related
