### ISSUE TITLE
Drag&Drop module creates copy of module

### ISSUE THREAD

**Issue by holgerhennig** [CellProfiler/CellProfiler#1857] opened 2016-03-17 17:10 UTC
Drag&Drop a module should move the module to the new position. Instead, CP creates a copy of the module at the new position and keeps the module at the old position (so that in the end the module exists twice).
CP Version: Beta 2.2.0

**Comment by dlogan** [comment] 2016-06-09 13:13
This is a serious UI problem ... mostly because I forgot about it and it just bit me again 😉

**Comment by AnneCarpenter** [comment] 2016-09-03 00:51
Duplicate of #1701 - closing. Something of a miracle that @braymp  didn't catch the duplicate, he somehow has photographic memory of all Github issues ever.

**Closed by AnneCarpenter** 2016-09-03 00:51 UTC
Labels: Bug, Layout and usability, Mac
