### ISSUE TITLE
MeasureObjectintensity: IndexError if label missing in a segmentation mask

### ISSUE THREAD

**Issue by votti** [CellProfiler/CellProfiler#3582] opened 2018-06-06 07:54 UTC
The `measureobjectintensity` module seems to have an issue, if a label is missing in the segmentation mask, i.e. not all labels 1:N are present.

For me the error occurred in a pipeline where I identify primary objects, filter them using `FilterObjects` and the use `IdentifySecondaryObjects` using the filtered objects as input objects.
I also encountered it after using `ResizeObjects` - another module that can produce such segmentation masks with missing labels.
Generally I think it would be important that missing labels are supported.

Error message:
```
> integrated_intensity[lindexes - 1] = centrosome.cpmorphology.fixup_scipy_ndimage_result(scipy.ndimage.sum(limg, llabels, lindexes))
E                       IndexError: index 1 is out of bounds for axis 0 with size 1

../../cellprofiler/modules/measureobjectintensity.py:406: IndexError
```

I also wrote a test to cover that case :
https://github.com/BodenmillerGroup/CellProfiler/blob/831f6affe1dcebbc8757bea84c48a10c4035060a/tests/modules/test_measureobjectintensity.py#L994

**Comment by apahl** [comment] 2018-06-19 08:04
The error also occurs for me with the same use case as @bgriffen (identify Primary Objects as "nuclei" then create Secondary Objects as "cells" using propagation from nuclei objects (no filtering)). This is for the latest version of CellProfiler  3.1.3 (commit cfac37b0e9ac from Jun 7th), on a Linux cluster.
I encountered this error after upgrading CellProfiler and my cppipe pipelines to 3.1.3.

Here is the traceback:

```
Error detected during run of module MeasureColocalization
Traceback (most recent call last):
  File "[...]/.conda/envs/cellprof/lib/python2.7/site-packages/CellProfiler-3.1.3-py2.7.egg/ce
llprofiler/pipeline.py", line 1779, in run_with_yield
    self.run_module(module, workspace)
  File "[...]/.conda/envs/cellprof/lib/python2.7/site-packages/CellProfiler-3.1.3-py2.7.egg/ce
llprofiler/pipeline.py", line 2031, in run_module
    module.run(workspace)
  File "[...]/.conda/envs/cellprof/lib/python2.7/site-packages/CellProfiler-3.1.3-py2.7.egg/ce
llprofiler/modules/measurecolocalization.py", line 284, in run
    object_name)
  File "[...]/.conda/envs/cellprof/lib/python2.7/site-packages/CellProfiler-3.1.3-py2.7.egg/cellprofiler/modules/measurecolocalization.py", line 571, in run_image_pair_objects
    std1 = np.sqrt(fix(scind.sum((first_pixels - mean1[labels - 1]) ** 2,
IndexError: index 161 is out of bounds for axis 0 with size 161
Tue Jun 19 09:42:13 2018: Image # 721, module MeasureColocalization # 10: CPU_time = 4.43 secs, Wall_time = 4.50 secs
```

Many thanks for your help!

Kind regards,  
Axel

**Comment by bethac07** [comment] 2018-06-19 21:17
Can one (or more) of you upload images plus a pipeline to help us replicate the issue? Thanks!

**Comment by apahl** [comment] 2018-06-20 08:10
Hi Beth,  

thanks for coming back to this.

I have checked out the latest commit (c11b509c4572f) from yesterday, but the problem persists.

Please find enclosed a single-image example which reproduces the error.
[cp_error.zip](https://github.com/CellProfiler/CellProfiler/files/2118396/cp_error.zip)

The pipeline was started with this command:

```
cellprofiler -c -p /home/pahl/cp_error/180611_gwdg.cppipe -r \
             --file-list=/home/pahl/cp_error/images.txt \
             -o /home/pahl/cp_error/output -L 10 \
             -t /home/pahl/cp_error/tmp
```

Many thanks.

Kind regards,  
Axel

**Comment by votti** [comment] 2018-08-06 21:40
Hi there,
I just run again into this issue in CP3.1.5 (both in Ubuntu installed from source as well from a Windows install from the Website).

Attached a small example.

The pipeline can be started with:
`cellprofiler -c -p ./measure_missing_obj.cppipe -r --file-list=./testfiles.txt -o out`

My workaround is currently to not load the mask as an `Object` in `Names and Types` but as a grayscale image and then  use `ConvertImageToObjects` with using `Preserve original labels` as `False`.
[issue_3583.zip](https://github.com/CellProfiler/CellProfiler/files/2264178/issue_3583.zip)

The error is still the same as with the test I previously wrote in the first post.

**Comment by jwindhager** [comment] 2018-08-09 10:34
Experiencing this as well. Any updates on this issue?

**Comment by votti** [comment] 2018-08-14 08:09
I also made a reproducible example, that `displaydataonimage` doesn't deal with missing labels:
The pipeline can be started with:
`cellprofiler -c -p ./missing_display.cppipe -r --file-list=./testfiles.txt -o ./out`

It first tries to display the `x position` on an image where the mask has been relabeled (=guaranteed continuous labels) and then when it uses the original mask with missing labels, which fails with an indexing error.

`img = colors[labels, :3] * pixel_data[:, :, np.newaxis]

Index Error: index 3707 is out of bounds for axis 9 with size 3707`

[issue_3583_missingdisplay.zip](https://github.com/CellProfiler/CellProfiler/files/2286024/issue_3583_missingdisplay.zip)

**Comment by votti** [comment] 2018-08-14 11:38
@bgriffen I think this issue should really not be about how IdentifySecondaryObjects can break generate primary-secondary objects with differing numbers. As-is CellProfiller does not guarantee this and thus explicilty returns the `primary_Parent_secondary` relationship.

The problem is more that the relationship between the label in segmentation masks and the cellprofiler measurements can be potentially lost in the current implementation. I think this is extremely dangerous as a lot of visualizations rely on the fact that `ObjectNumbers `match labels in segmentation masks!
Also if this is not guaranteed the only way to match ObjectNubmers with Labels is e.g. by matching positions which is really not as trivial as it should be.

I crafted an example pipeline with a Jupyter analysis notebook demonstrating the problem:
[issue_3583_label_missmatch.zip](https://github.com/CellProfiler/CellProfiler/files/2286705/issue_3583_label_missmatch.zip)

Run as:
`cellprofiler -c -p ./label_missmatch.cppipe -r --file-list=./testfiles.txt -o ./out`

In the CP pipeline I once process an object mask with and without missing objects (called 'Original'(=with missing) and 'Relabeled'(=without missing)). Then  I save the results. In the Jupyter notebook I then compare the cell data and the mask labels. I find that indeed cellprofiler internally, without any warning seems to relable `ObjectNumbers`, which makes it no longer possible to directly map CP measurements on the corresponding segmentation mask.
I find this a real problem in my view!

"Luckily" most 'measurement' modules currently just throw an indexing error if they encounter missing labels, thus the effect of this problem is likely not so wide spread (but super annoying). Still it needs to be fixed!

The Jupyter Notebook of the analysis can be found here: https://gist.github.com/votti/08870efac40c677abb2dc428d58e35d3

**Comment by votti** [comment] 2018-09-12 06:44
Hi there,

In the meanwhile this issue is also being discussed on the image.sc forum: https://forum.image.sc/t/index-is-out-of-bounds-error/19078/5

Thus I was wondering what the 'officially' proposed workaround for this issue for now is and if a fix is being worked at.

Thanks a lot for your efforts!

**Comment by AetherUnbound** [comment] 2018-09-13 04:30
@votti thanks for pinging on this. This has come up in a number of different modules, namely `RelateObjects` as well. I think there's a common root cause to all of these, and I think I should have some time to look into this in the near future :) I'm sorry that I don't have more time to address this, but THANK YOU for the super detailed thread; it will be incredibly helpful when I do have a spare moment to look into this!

**Comment by Swarchal** [comment] 2018-09-27 15:46
As a really simple bodge I've tried reverting [this commit](https://github.com/CellProfiler/CellProfiler/commit/158dcfca061baf2fb03d5e950cfefa9f1e42e11e#diff-dbeb543178b826d1d668fd53fe3b5105L124), and while now previously broken pipelines are running again I'm worried I've broken some parent -> child object_number mapping.

I had a very quick check of object x,y co-ordinates and object numbers [here](https://gist.github.com/Swarchal/22344cfda56a64883c4b759174330299), but if like us you're just using image averages it might suffice.

**Comment by santoshhariharan** [comment] 2018-11-16 13:31
Hello,

I am new to CellProfiler and trying to use the program in headless mode on a cluster. I am also getting similar error (Please see below) in MeaureColocalization module. I tried the same pipeline with the older version (2.1.2). Currently we have 3.1.5. Any advise is appreciated. Here is the trace

Thu Nov 15 16:44:25 2018: Image # 2, module Images # 1: CPU_time = 0.00 secs, Wall_time = 0.00 secs
Thu Nov 15 16:44:25 2018: Image # 2, module Metadata # 2: CPU_time = 0.00 secs, Wall_time = 0.00 secs
Thu Nov 15 16:44:26 2018: Image # 2, module NamesAndTypes # 3: CPU_time = 2.45 secs, Wall_time = 2.84 secs
Thu Nov 15 16:44:28 2018: Image # 2, module Groups # 4: CPU_time = 0.00 secs, Wall_time = 0.00 secs
Thu Nov 15 16:44:28 2018: Image # 2, module CorrectIlluminationApply # 5: CPU_time = 0.22 secs, Wall_time = 0.23 secs
Thu Nov 15 16:44:29 2018: Image # 2, module MeasureImageQuality # 6: CPU_time = 8.77 secs, Wall_time = 8.87 secs
Thu Nov 15 16:44:37 2018: Image # 2, module MeasureImageQuality # 7: CPU_time = 0.27 secs, Wall_time = 0.26 secs
Thu Nov 15 16:44:38 2018: Image # 2, module FlagImage # 8: CPU_time = 0.00 secs, Wall_time = 0.00 secs
Thu Nov 15 16:44:38 2018: Image # 2, module IdentifyPrimaryObjects # 9: CPU_time = 0.71 secs, Wall_time = 0.71 secs
Thu Nov 15 16:44:39 2018: Image # 2, module IdentifySecondaryObjects # 10: CPU_time = 0.61 secs, Wall_time = 0.66 secs
Thu Nov 15 16:44:39 2018: Image # 2, module IdentifyTertiaryObjects # 11: CPU_time = 0.10 secs, Wall_time = 0.10 secs
Error detected during run of module MeasureColocalization
Traceback (most recent call last):
  File "/home/harihs06/CellProfiler/cellprofiler/pipeline.py", line 1782, in run_with_yield
    self.run_module(module, workspace)
  File "/home/harihs06/CellProfiler/cellprofiler/pipeline.py", line 2034, in run_module
    module.run(workspace)
  File "/home/harihs06/CellProfiler/cellprofiler/modules/measurecolocalization.py", line 288, in run
    object_name)
  File "/home/harihs06/CellProfiler/cellprofiler/modules/measurecolocalization.py", line 575, in run_image_pair_objects
    std1 = np.sqrt(fix(scind.sum((first_pixels - mean1[labels - 1]) ** 2,
IndexError: index 19 is out of bounds for axis 0 with size 19

**Comment by ranka47** [comment] 2019-05-30 15:19
I was facing the same error in CP 3.1.5
After identifying the primary objects (nucleus) and the secondary objects (cytoplasm), the pipeline was supposed to measure the intensity. However, it raised the `IndexError`. 

However, the pipeline is working fine for CP 3.1.8. I guess it has been fixed in the latest version.

**Comment by apahl** [comment] 2019-06-03 10:43
@ranka47 thanks for letting us know. Because of this error, I have started our project with CP 3.0.0 and we are therefore currently stuck with this version.

Kind regards,  
Axel

**Comment by bethac07** [comment] 2020-03-24 21:16
Closing since reported as fixed in 318, reopen if still present.

**Closed by bethac07** 2020-03-24 21:16 UTC
