### ISSUE TITLE
Increase or remove maximum memory limits from preferences.  

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2826] opened 2017-07-26 22:07 UTC
The CP preferences window only allows you to allot a maximum of 64GB of memory; now that systems with more than that exist in (semi-)common usage, we should increase or remove this maximum.  Relevant source code is [here](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/gui/preferencesdlg.py#L338-L342).

**Comment by mcquin** [comment] 2017-07-26 22:14
If we go the remove route, users can set their JVM initial and maximum heap sizes with:

```
set JAVA_OPTS="-Xms128m -Xmx256m"
```

**Comment by mcquin** [comment] 2018-01-24 19:42
Duplicate of #1938

**Closed by mcquin** 2018-01-24 19:42 UTC
Labels: Enhancement
