### ISSUE TITLE
FilterObjects: Relabeled additional objects have no parents

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1404] opened 2015-07-14 20:24 UTC
Demonstrated with attached project file.

In this project (adapted from welcome screen pipeline), nuclei are filtered to give new nuclei objects, and the associated secondary cells are relabeled as well. 

The filtered nuclei have the original nuclei as parents (first DisplayDataOnImage), but the filtered cells have no parents (2nd DisplayDataOnImage). I assume that they should have the original cells as parents as well.

Attachments:
http://cellprofiler.org/issues/uploaded/pENZrJ/issue.cpproj

**Comment by LeeKamentsky** [comment] 2015-07-31 15:43
I think they should have the relabeled parents as parents, Parent_NewNuclei in this case. (if you really press me, I'll say that you should be able to figure the object number of the parent Nuclei thusly: Parent_Cell[NewCell] -> Parent_Nuclei[Cell]) -> Parent_Nuclei[New_Nuclei] or better yet, through the relationships table)

Oh what the heck - let's do them all!

**Comment by LeeKamentsky** [comment] 2015-07-31 19:41
I'm having second thoughts about this. FilterObjects assumes that the additional objects are labeled identically.@braymp could you talk to me about the use case? I think the values for Parents_Nuclei for FilteredCells will be the same as Parents_Cells - otherwise the assumption that Cells and Nuclei are labeled similarly is wrong.

**Comment by braymp** [comment] 2015-07-31 19:48
I've always used the additional objects option to relabel secondary objects assuming that the associated primary objects were filtered above. 

I agree: anything other than that is probably not good. Probably good to put a validation check that the filtered/add'l objects are a matched primary/secondary set.

**Comment by AnneCarpenter** [comment] 2016-09-02 15:29
I'm moving this to future consideration for now; it would need a clearer description of the recommended course of action to start work on it, but I'm not sure whether the issue is a major concern for anyone.

**Closed by AnneCarpenter** 2016-09-02 15:29 UTC
Labels: Bug

**Comment by braymp** [comment] 2016-09-02 16:32
My recommendation: Have FilterObjects show an error if the additional relabeled objects are *not* primary/secondary/tertiary to the filtered objects.
