### ISSUE TITLE
Update pyzmq version

### ISSUE THREAD

**Issue by DavidStirling** [CellProfiler/CellProfiler#4462] opened 2021-09-10 19:01 UTC
Installing CP4 from source can be a bit painful due to the need to build several packages, it might be good to try to minimise build steps wherever possible.

`setup.py` currently specifies `pyzmq==18.0.1` from #3760. Per [their changelog](https://pyzmq.readthedocs.io/en/latest/changelog.html) this is actually from before official Python 3.8 support and therefore only Python 3.7 wheels are available over pip for that version. It looks like 18.1.1 should provide compatible wheels without breaking changes. It may be possible to use even newer versions but that'd require testing.

**Comment by iosonofabio** [comment] 2021-09-15 05:42
I can confirm it works on my arch linux machine with `python-pyzmq 22.2.1` and Python 3.9. Hope it's useful

**Comment by MathiasBeller** [comment] 2022-01-25 15:43
Sorry for the probably stupid question, but I am also having issues with the build install and expect that this is based on the pyzmq version problem. I specified a more recent version in the setup.py file (18.1.1), yet now I get a different error: 

"The conflict is caused by:
    cellprofiler 4.2.1 depends on pyzmq==18.1.1
    cellprofiler-core 4.2.1 depends on pyzmq==18.0.1"

Can I fix this as well somehow? Thank you very much in advance for your help! Mathias

**Comment by DavidStirling** [comment] 2022-01-25 17:50
You'll need to modify cellprofiler-core as well.

**Comment by MathiasBeller** [comment] 2022-01-25 20:15
Thanks - I saw now this repo. I guess I need to clone this also for the build install and put it next to the cloned cellprofiler repo? Or is there another trick? The install instructions (https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28Windows%29) are not clear in this respect.

**Comment by DavidStirling** [comment] 2022-01-25 21:40
Cloning and installing that repo should work. Usually you can use the packaged version of core but since this change needs to be made in both there's no good way around that.

**Comment by MathiasBeller** [comment] 2022-01-26 06:51
Worked like a charm! Thank you very much!!!

**Comment by bethac07** [comment] 2022-07-15 19:24
Fixed in #4503

**Closed** 2022-07-15 19:23 UTC
Labels: Environment/Install
