### ISSUE TITLE
ExportToDatabase doesn't respect metadata when specifying file output location

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2580] opened 2017-02-07 16:59 UTC
In ExportToDatabase, at least with the 'SQLite' option, if you use a piece of metadata in the 'Ouput file location' box (either as 'Elsewhere' or one of the subfolder options), it doesn't actually use the metadata that you give it- ie if all of the images in my image set have an extracted piece of metadata called 'SubfolderName' with a value of 'Subfolder1' , and I set my 'Output file location' as `Default Output Subfolder -> 'SubfolderName'`, the .db is created in the `Default Output Folder`, not `Default Output Folder/Subfolder1`.  Subfolders DO otherwise work fine as long as it's just a text value and not a piece of metadata.

I can pretty easily understand why this might be (CP isn't going to assume all images have the same metadata, so it wants a universal place to put the images), but if the metadata isn't used we shouldn't let it be specified.

**Comment by braymp** [comment] 2017-02-07 18:33
Duplicate of https://github.com/CellProfiler/CellProfiler/issues/1276?

**Comment by bethac07** [comment] 2017-02-07 18:44
Related but not sure if duplicate- this is for SQLite, which should be being written at the beginning not in `post_run` (I think).  I think just removing Metadata based specification from that module entirely is probably the best solution.

**Comment by bethac07** [comment] 2017-02-10 18:08
Ability to specify locations based on metadata will be remove in 3.0

**Comment by mcquin** [comment] 2017-04-19 19:35
Closing in favor of https://github.com/CellProfiler/CellProfiler/issues/2702

**Closed by mcquin** 2017-04-19 19:35 UTC
