### ISSUE TITLE
In Python 3 branch, removing an image from the file list is slow and makes the window black

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3780] opened 2019-07-01 17:42 UTC

**Comment by jeffsyang** [comment] 2019-07-08 20:43
Could this be retested please (after open PRs  for the python3 branch had been merged)? I wasn't able to reproduce the issue but maybe more details will help if the problem persists?

**Comment by DavidStirling** [comment] 2020-02-20 16:53
I'm also unable to reproduce this on master. Could it be Mac specific?

**Closed** 2020-03-24 21:52 UTC
