### ISSUE TITLE
Optionally disable using scrolling to change values in dropdown menus

### ISSUE THREAD

**Issue by joelostblom** [CellProfiler/CellProfiler#3726] opened 2019-03-07 16:58 UTC
When I teach people how to use CellProfiler, one of the most common errors they encounter is when they use the mouse scroll wheel to navigate up and down the options (e.g. in NamesAndTypes), but accidentally hovers over a dropdown menu and changes the value instead of scrolling the page without noticing it. This is very confusing to troubleshoot, because in their mind they have never touched the setting that is giving the error (e.g. maybe they accidentally change "Does contain" to "Does not contain" in NamesAndTypes), so they often get stuck here.

The current behavior of the scroll wheel means that if I use it to navigate the options pages, I need to double check every single option on those pages when I encounter an error because I am not sure where I might have hovered over a dropdown box when trying to scroll the page. My own workaround is to not use the scroll wheel at all and drag the scroll bar instead, but the scroll wheel behavior is quite ingrained in people so many still use it by habit.

Is there a way to disable the behavior where the scroll wheel can change the values in the dropdown menus (I could not find one in the preferences), or would you consider adding an option to disable this?

**Comment by DavidStirling** [comment] 2020-02-20 17:02
Duplicate of #2363, being discussed in #3909.

**Comment by DavidStirling** [comment] 2020-02-20 17:03
Duplicate of #2363

**Comment by DavidStirling** [comment] 2020-02-20 17:04
Currently being discussed in #3909.

**Closed** 2020-02-26 19:10 UTC
